### PR TITLE
fix: Leave meeting button oversize area

### LINKED ISSUE #24540: Leave Meeting button has an oversized clickable area
**Describe the bug**
The Leave Meeting button has a clickable area larger than its visible bounds. As a result, clicks near the button—but not directly on it—can still trigger the leave meeting action.

**To Reproduce**
1. Join a meeting
2. Click near the edges of the Leave Meeting button, without clicking directly on it
3. Observe that the action is triggered even though the cursor does not indicate a clickable area

**Expected behavior**
The Leave Meeting button should only be clickable when the cursor is positioned directly over the visible button area, and the pointer cursor should accurately reflect that.

**Actual behavior**
Clicks in the surrounding area trigger the Leave Meeting action, despite no visual indication (e.g., pointer cursor) that the area is interactive.

**Screenshots**
Image

Image

**BBB version:**
dev30
dev31

**Additional context**

### PR DESCRIPTION
**Pull request by bittoby**
### What does this PR do?

This PR fixes the "Leave Meeting" button having a clickable area larger than its visible bounds. The issue occurred because margins were applied directly to the button element, and clicks in the margin area would trigger the dropdown menu unexpectedly.

The fix moves the margin styles from `LeaveButton` to a new `LeaveMeetingWrapper` component that wraps the `BBBMenu`. Since the wrapper has no click handler, clicks in the margin area no longer trigger the menu.

**Changes:**
- Added `LeaveMeetingWrapper` styled component in `leave-meeting-button/styles.js`
- Moved `margin-left: 1.0rem` and `margin-right: 0.5rem` from `LeaveButton` to the wrapper
- Wrapped `BBBMenu` with `LeaveMeetingWrapper` in `leave-meeting-button/component.jsx`

### Closes Issue(s)

Closes #24540

### Motivation

The Leave Meeting button's clickable area extended into the margin space around the button. This caused unintended behavior where clicking near (but not on) the button would trigger the leave meeting dropdown menu, despite no visual indication of interactivity. This could lead to accidental meeting exits, which is particularly problematic for a critical action like leaving a meeting.

### How to test

1. Join a meeting as a moderator
2. Locate the red "Leave Meeting" button in the top-right corner
3. Click directly on the button → dropdown menu should open ✅
4. Close the menu (click outside or press ESC)
5. Click in the area to the left of the button (in the margin/spacing area) → menu should NOT open ✅
6. Click in the area to the right of the button (in the margin/spacing area) → menu should NOT open ✅
7. Verify the button appearance and spacing look unchanged from before ✅
8. Test on mobile viewport size to ensure layout is not affected ✅

### More

- The fix only affects the Leave Meeting button component; no changes to shared/common components
- Visual appearance and spacing remain identical to before
- Mobile behavior is preserved (no margins on mobile, same as original)

[1.webm](https://github.com/user-attachments/assets/eb02caf9-9937-413e-84e6-de22fadf1b67)

- [ ] Added/updated documentation

### CODE REVIEW

**Comment by antobinary** [comment]
Hi @bittoby ! Thank you for your contribution! Any chance you could send a CLA so we can move forward reviewing the code? https://github.com/bigbluebutton/bigbluebutton/pull/24544#issuecomment-3797144505

**Comment by antobinary** [comment]
CLA received, thanks!

**Review by Arthurk12 — CHANGES_REQUESTED** [review]
Hey @bittoby Thanks for the contribution and for fixing the reported issue - the PR does solve the oversized clickable area for the end meeting button.

However, the fix was applied to the generic menu component, and while it works for this specific button, tests show it causes regressions in other buttons that reuse the same component. The problem is that the checks included in the generic menu component are too strict and they inadvertently disable the extended click areas that other buttons rely on for accessibility, as well as breaking interactions for buttons with complex internal structures like text labels next to icons.

I would recommend trying another approach, which is adjusting the padding/margin of the meeting end button specifically.

**Comment by bittoby** [comment]
@Arthurk12  Thank you for your feedback. I will fix it.

**Comment by bittoby** [comment]
@Arthurk12  Could you plz review again?

**Review by Arthurk12 — CHANGES_REQUESTED** [review]
I can still reproduce the issue:

Image

**Comment by bittoby** [comment]
Sorry, I will check it again and push soon

**Comment by bittoby** [comment]
@Arthurk12 
I fixed all. Please review again. thank you

**Comment by bittoby** [comment]
Hi, @Arthurk12 . Sorry for tagging you again. If possible, could you review this PR again soon? I updated based on your feedback and tested carefully. I uploaded test result on the PR description. Thanks.

**Comment by bittoby** [comment]
@antobinary @Arthurk12 Please check this PR and would appreciate merge it if it has no problem.

**Comment by antobinary** [comment]
Hi @bittoby 
We appreciate the pull request. We did two reviews and a test the week you sent it :)
It's on our list to review again. No need to tag us repeatedly, we are working on other aspects of BigBlueButton right now, it's a big project.

File: bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/styles.js [hunk 1]
```diff
@@ -2,6 +2,17 @@ import styled from 'styled-components';
 import { smallOnly } from '/imports/ui/stylesheets/styled-components/breakpoints';
 import Button from '/imports/ui/components/common/button/component';
 
+const LeaveMeetingWrapper = styled.div`
+  display: inline-block;
+  
+  /* Margins moved here from LeaveButton to fix clickable area issue */
```
Comment (Arthurk12) [inline bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/styles.js]: Remove comments in styles:
```suggestion
```

File: bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/styles.js [hunk 2]
```diff
@@ -2,6 +2,17 @@ import styled from 'styled-components';
...
+  /* Only apply margins on non-mobile to match original button behavior */
```
Comment (Arthurk12) [inline bigbluebutton-html5/imports/ui/components/nav-bar/leave-meeting-button/styles.js]: Remove comments in styles:
```suggestion
```

**Review by Arthurk12 — CHANGES_REQUESTED** [review]
LGTM! The issue is solved. Just a minor change: removing comments inside styles.
