### PR TITLE
fix: Listen-only participants show misleading crossed-out microphone icon instead of headphones icon

### LINKED ISSUE #23479: Listen-only participants show misleading crossed-out microphone icon instead of headphones icon
**Describe the bug**
Listen-only participants display a crossed-out microphone icon in the participants list, even when they don't have permission to activate mic. This icon is misleading as it suggests mic could be enabled when it cannot.

**To Reproduce**
1. Join a BigBlueButton meeting as a listen-only participant
2. In the participants list the icon displayed is a crossed-out microphone icon

**Expected behavior**
Listen-only participants should display a headphones icon (as in previous BBB versions) to clearly indicate their listen-only status, rather than a crossed-out microphone which suggests disabled (but generally available) microphone capability.

**Actual behavior**
A crossed-out microphone icon is displayed for listen-only participants, creating confusion about their actual permissions and capabilities.

**Screenshots**
Image

**BBB version:**
BigBlueButton 3.0.9

**Desktop (please complete the following information):**
 - OS: macOS 15.5
 - Browser: Safari
 - Version: 18.5

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

introduces a new boolean value `listenOnlyInputDevice` in voice information to track listen only state when transparentListenOnly is enabled

#### before

https://github.com/user-attachments/assets/341ab84c-bdb4-4f87-bdaf-221dbab8ba6e

#### after

https://github.com/user-attachments/assets/9236bf53-33bd-435c-b897-a6d53e175b86

### Closes Issue(s)
Closes #23479

### How to test
1. create a meeting with `public.media.transparentListenOnly: true`
1. join a meeting as a listen-only participant or join with a microphone and then switch the input device to "No microphone (listen only)"
2. check the icon displayed in the userlist for that user

### CODE REVIEW

File: akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp.scala [hunk 1]
```diff
@@ -768,6 +771,31 @@ object VoiceApp extends SystemConfiguration {
       }
   }
 
+  def setListenOnlyInputInVoiceConf(
+    liveMeeting:              LiveMeeting,
+    outGW:                    OutMsgRouter,
+    userId:                   String,
+    listenOnlyInputDevice:    Boolean
+  )(implicit context: ActorContext): Unit = {
```
Comment (gustavotrott) [inline akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/VoiceApp.scala]: This function doesn't require a context.

```suggestion
  ): Unit = {
```

File: akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/SetUserListenOnlyInputCmdMsgHdlr.scala [hunk 2]
```diff
@@ -0,0 +1,54 @@
...
+  this: BaseMeetingActor =>
+
+  val liveMeeting: LiveMeeting
+  val outGW: OutMsgRouter
+
+  def handleSetUserListenOnlyInputCmdMsg(msg: SetUserListenOnlyInputCmdMsg) {
+    if (msg.body.userId != msg.header.userId && (permissionFailed(
+      PermissionCheck.MOD_LEVEL,
+      PermissionCheck.VIEWER_LEVEL, liveMeeting.users2x, msg.header.userId
+    ))) {
```
Comment (gustavotrott) [inline akka-bbb-apps/src/main/scala/org/bigbluebutton/core/apps/voice/SetUserListenOnlyInputCmdMsgHdlr.scala]: I'm not sure this validation is appropriate.
As I see it, only the user themselves should be allowed to set this flag, so checking the Role doesn't seem relevant in this case.

File: bbb-graphql-actions/src/actions/userSetListenOnlyInput.ts [hunk 3]
```diff
@@ -0,0 +1,30 @@
...
+  };
+
+  const header = { 
+    name: eventName,
+    meetingId: routing.meetingId,
+    userId: routing.userId
+  };
+
+  const body = {
+    userId: routing.userId,
```
Comment (gustavotrott) [inline bbb-graphql-actions/src/actions/userSetListenOnlyInput.ts]: It might not be necessary to include `userId` in the body.
I’m aware there are other similar cases where `userId` is included even though it always matches the one in the header.
But for new actions, let’s try to follow a pattern like `userSetTalking`.

**Comment by gustavotrott** [comment]
I tried to test with Dial-in users, but they are always joining muted.
This problem was not introduced in this PR, I'm just mentioning to say I was not able to test it.
I'll take a look if it's expected or an issue.

image

File: bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala [hunk 4]
```diff
@@ -190,6 +190,16 @@ case class MuteUserCmdMsg(
...
 
+/**
+ * Sent by client to set input id listen only value for user in the voice conference.
+ */
+object SetUserListenOnlyInputCmdMsg { val NAME = "SetUserListenOnlyInputCmdMsg" }
+case class SetUserListenOnlyInputCmdMsg(
+    header: BbbClientMsgHeader,
+    body:   SetUserListenOnlyInputCmdMsgBody
+) extends StandardMsg
+case class SetUserListenOnlyInputCmdMsgBody(userId: String, listenOnlyInputDevice: Boolean)
```
Comment (gustavotrott) [inline bbb-common-message/src/main/scala/org/bigbluebutton/common2/msgs/VoiceConfMsgs.scala]: I think it's not being used:

```suggestion
case class SetUserListenOnlyInputCmdMsgBody(listenOnlyInputDevice: Boolean)
```

**Review by gustavotrott — APPROVED** [review]
lgtm, well done!!
