### PR TITLE
Fix restore presentation button overlap (Mobile - Presenter)

### LINKED ISSUE #8290: Restore Presentation button is overlapping screenshare/video button when user is presenter on mobile.
Phone: Iphone 8
OS: IOS 13.1.3
Browser: Safari 13

ezgif com-video-to-gif

### PR DESCRIPTION
**Pull request by KDSBrowne**
Closes #8290

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx [hunk 1]
```diff
@@ -78,11 +78,7 @@ class ActionsBar extends PureComponent {
             : null
           }
         </div>
-        <div
-          className={
-            amIPresenter ? cx(styles.centerWithActions, actionBarClasses) : styles.center
-          }
-        >
+        <div className={cx(actionBarClasses)}>
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx]: can remove the `cx` and also remove the import of cx

Comment (KDSBrowne) [reply bigbluebutton-html5/imports/ui/components/actions-bar/component.jsx]: Removing the `cx` breaks the styling 
image

**Comment by capilkey** [comment]
This PR should be merged into 2.2-release.
