### PR TITLE
Fix viewer webcam not unsharing when lock setting is enable

### LINKED ISSUE #8035: Webcams don't stop sharing when they are locked
Steps to reproduce:
1. Join with two clients (one view, one moderator)
2. Share a webcam from the view
3. Lock webcams

Expected result:
The viewers webcam should stop sharing and release and button be disabled.

Actual result:
The other clients hide the viewers webcam, but it's still sharing in the viewer's client and it can't be stopped because the webcam button is disabled.

image

### PR DESCRIPTION
**Pull request by Tainan404**
Closes #8035.

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/video-provider/container.jsx [hunk 1]
```diff
@@ -16,6 +19,12 @@ export default withTracker(props => ({
   meetingId: VideoService.meetingId(),
   users: VideoService.getAllWebcamUsers(),
   userId: Auth.userID,
+  userIsLocked: !!Users.findOne({
+    userId: Auth.userID,
+    locked: true,
+    role: { $ne: ROLE_MODERATOR },
+  }, { find: {} }) && VideoService.webcamsLocked(),
```
Comment (capilkey) [inline bigbluebutton-html5/imports/ui/components/video-provider/container.jsx]: There's no option for collections called `find`. The option is `fields`.
