### PR TITLE
fix(whiteboard): Add ability to limit history stack size

### LINKED ISSUE #23886: Whiteboard Performance Degradation overtime
**Describe the bug**
Whiteboard pen tool becomes laggy and unresponsive after approximately 90 minutes of continuous use during tutoring sessions. Writing becomes choppy and deformed, making the whiteboard unusable.

**To Reproduce**
1. Start BBB session with 2 participants (tutor + student)
2. Use whiteboard extensively with heavy drawing for more than an hour
3. Continue session for 90+ minutes with frequent drawing/erasing
4. Observe progressive pen lag and responsiveness issues
5. Hard refresh browser temporarily fixes the issue

**Expected behavior**
Whiteboard should remain responsive throughout 2-hour sessions without performance degradation.

**Actual behavior**
- Pen becomes increasingly laggy after ~90 minutes
- Writing appears choppy and deformed
- Hard refresh temporarily resolves the issue
- Audio/video remain unaffected throughout

**BBB Version**
```bash
BigBlueButton Server 3.0.10 (3029)
```

**Version Timeline**
- v3.0.7: No issues reported
- v3.0.13: Issue first appeared
- v3.0.10: Issue persists (current version)

**Environment**
**Server:**
- 8 vCPUs, 32GB RAM, SSD storage
- Ubuntu 22.04.5 LTS
- Typically <10 concurrent users
- Server resources are not constrained

**Client:**
- **All users affected** regardless of device/browser
- Windows 10/11, macOS, Android, IOS, various hardware specs
- Chrome, Firefox, Safari - **all browsers affected**
- Issue occurs across different client machines

**Session Details**
- tutoring sessions (intensive whiteboard use)
- 2-5 participants per session
- 90-120 minute duration
- Heavy annotation usage 

**Optimization Attempts**
We have tried various server-side optimizations:

```yaml
# Increased annotation limits
maxNumberOfAnnotations: 600  # from default 300

# Optimized processing
annotationsQueueProcessInterval: 30  # from 60ms
cursorInterval: 100  # from 150ms

# Database connection optimization
HASURA_GRAPHQL_PG_CONNECTIONS: 15  # from 10
```

**None of these optimizations resolved the core issue.**

This significantly impacts our tutoring platform where whiteboard interaction is critical for student learning.

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

This PR adds the ability to limit the stack size of the history manager of tldraw. The maximum size is configurable.

First step in order to tackle https://github.com/bigbluebutton/bigbluebutton/issues/23886.

### Closes Issue(s)

Partially closes #23886

### Motivation

The history stack size can grow indefinitely along the session.

### More

It depends on https://github.com/bigbluebutton/tldraw/pull/34

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx [hunk 1]
```diff
@@ -1144,6 +1144,7 @@ const Whiteboard = React.memo((props) => {
   };
 
   const handleTldrawMount = (editor) => {
+    editor.history.setMaxStackSize(window.meetingClientSettings.public.whiteboard.maxHistoryStackSize);
```
Comment (ramonlsouza) [inline bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx]: could you add a check to verify that `setMaxStackSize` exists before calling it?
if it's missing, log something like: "Could not set whiteboard max history stack size - feature not available" so the whiteboard still works even without that function.

**Review by ramonlsouza — APPROVED** [review]
