### PR TITLE
Fix WebcamsOnlyForModerator to not show any viewer's camera on recording.

### LINKED ISSUE #9789: webcamsOnlyForModerator is not applied in recording
**Describe the bug**
I've set webcamsOnlyForModerator=true in bigbluebutton.properties. It's working in live stream. But users can still see other users in recorded playback.

### PR DESCRIPTION
**Pull request by GuiLeme**
### What does this PR do?

Makes `WebcamsOnlyForModerator` config to not show any viewer's camera on recording.

### Closes Issue(s)

Closes #9789 

### More

To test this PR it is mandatory to both run `akka-apps` (along with building `bbb-common-message`) and the `recording` from the code. The `akka-apps` component is responsible for storing the newly created events, and the recording has the functional part of this PR.

It is worth warning the reviewer to pay attention to the recording configuration (make sure that the `webrtc-sfu` component is well configured to store the webcam videos). In case of doubts, feel free to contact me.

### CODE REVIEW

**Comment by GuiLeme** [comment]
@gustavotrott, Good point, I am implementing it right away. From what I see,  `showModeratorViewpoint=false` would be the best choice, since we can expand this to other meeting locks in the future and not just ignoring `webcamsOnlyForModerator` parameter.

**Comment by prlanzarin** [comment]
> @gustavotrott, Good point, I am implementing it right away. From what I see, `showModeratorViewpoint=false` would be the best choice, since we can expand this to other meeting locks in the future and not just ignoring `webcamsOnlyForModerator` parameter.

You might want to get input from kepstin about that since he was the one that [originally requested it to be configurable](https://github.com/bigbluebutton/bigbluebutton/issues/9789#issuecomment-1074214481).

File: akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala [hunk 1]
```diff
@@ -116,6 +116,8 @@ class RedisRecorderActor(
       case m: RecordStatusResetSysMsg               => handleRecordStatusResetSysMsg(m)
       case m: WebcamsOnlyForModeratorChangedEvtMsg  => handleWebcamsOnlyForModeratorChangedEvtMsg(m)
       case m: MeetingEndingEvtMsg                   => handleEndAndKickAllSysMsg(m)
+      //      case m: BroadcastConfReqMsg                   => handleBroadcastConfigRespMsg(m)
```
Comment (prlanzarin) [inline akka-bbb-apps/src/main/scala/org/bigbluebutton/endpoint/redis/RedisRecorderActor.scala:119]:
```suggestion
```

File: akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/MeetingConfigurationEvent.scala [hunk 2]
```diff
@@ -0,0 +1,34 @@
...
+  setEvent("MeetingConfigurationEvent")
+
+  def setWebcamsOnlyForModerator(webcamsOnlyForModerator: Boolean) {
+    eventMap.put(WEBCAMS_ONLY_FOR_MODERATOR, webcamsOnlyForModerator.toString)
+  }
+}
+
+object MeetingConfigurationEvent {
+  val WEBCAMS_ONLY_FOR_MODERATOR = "webcamsOnlyForModerator"
+}
```
Comment (prlanzarin) [inline akka-bbb-apps/src/main/scala/org/bigbluebutton/core/record/events/MeetingConfigurationEvent.scala:34]: Prefer configuring your editor to leave a trailing newline at the end of text files - it's the pattern used by the majority of the project AFAIK.
This happens in StartConfigurationEvent.scala as well.

File: record-and-playback/core/lib/recordandplayback/generators/events.rb [hunk 3]
```diff
@@ -125,57 +177,203 @@ def self.create_webcam_edl(events, archive_dir)
...
 
-        # Add the video to the EDL
-        case event['eventname']
-        when 'StartWebcamShareEvent', 'StartWebRTCShareEvent'
-          videos[filename] = { :timestamp => timestamp }
-          active_videos << filename
+          # Add the video to the EDL
+          case event['eventname']
+          when 'StartWebcamShareEvent', 'StartWebRTCShareEvent'
+            userId = BigBlueButton::Events.get_id_from_filename(filename)
```
Comment (prlanzarin) [inline record-and-playback/core/lib/recordandplayback/generators/events.rb:253]: I thought it was requested that the userId event should be added to the share/stop events so that we would not need to use the filename as the main method of associating a camera stream to an userId.

If that was the case, this should be the fallback (in case the scripts are run over older recordings), not the default method. What's the motivation here?

Comment (GuiLeme) [reply record-and-playback/core/lib/recordandplayback/generators/events.rb:253]: Yeah, so during implementation, I realized that even if I had the `userId` at the start/stop events, that wouldn't really mean that the EDL entry item has that `userId`, for example: There might be cameras already open when the start/stop events are interpreted, and they, surely, don't have the same `userId` as the newly added.

And about the motivation, I thought that by putting the userId in the EDL, we could use it in the future with new features, but I can take it out.

**Comment by GuiLeme** [comment]
> > @gustavotrott, Good point, I am implementing it right away. From what I see, `showModeratorViewpoint=false` would be the best choice, since we can expand this to other meeting locks in the future and not just ignoring `webcamsOnlyForModerator` parameter.
> 
> You might want to get input from kepstin about that since he was the one that [originally requested it to be configurable](https://github.com/bigbluebutton/bigbluebutton/issues/9789#issuecomment-1074214481).

Ok, so, I talked to him, and he agreed with implementing it, he just asked me to change the location of the property from the `recording.yml` to the `bigbluebutton.yml`

File: bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java [hunk 4]
```diff
@@ -103,6 +104,7 @@ public class MeetingService implements MessageListener {
   private CallbackUrlService callbackUrlService;
   private HTML5LoadBalancingService html5LoadBalancingService;
   private SwfSlidesGenerationProgressNotifier notifier;
+  private Boolean webcamsOnlyForModerator;
```
Comment (gustavotrott) [inline bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java:107]: It seems to be never accessed. Consider removing it.

File: bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java [hunk 5]
```diff
@@ -1260,6 +1262,10 @@ public void stop() {
     enteredUserCleaner.stop();
   }
 
+  public void setWebcamsOnlyForModerator(boolean webcamsOnlyForModerator) {
+    this.webcamsOnlyForModerator = webcamsOnlyForModerator;
+  }
+
```
Comment (gustavotrott) [inline bbb-common-web/src/main/java/org/bigbluebutton/api/MeetingService.java:1268]: Not necessary once webcamsOnlyForModerator is being set in ParamsProcessor.

File: bigbluebutton-web/grails-app/conf/spring/resources.xml [hunk 6]
```diff
@@ -45,6 +45,7 @@ with BigBlueButton; if not, see <http://www.gnu.org/licenses/>.
     </bean>
 
     <bean id="meetingService" class="org.bigbluebutton.api.MeetingService" init-method="start" destroy-method="stop">
+        <property name="webcamsOnlyForModerator" value="${webcamsOnlyForModerator}"/>
```
Comment (gustavotrott) [inline bigbluebutton-web/grails-app/conf/spring/resources.xml:48]: It seems that `meetingService` doesn't need it anymore. Consider removing this.

File: record-and-playback/core/scripts/bigbluebutton.yml [hunk 7]
```diff
@@ -40,6 +40,12 @@ anonymize_chat: false
 # meta param: meta_bbb-anonymize-chat-moderators (true/false)
 anonymize_chat_moderators: false
 
+# By default, the locks are going to be applied and the viewer's point
+# of view is going to be showed here
+# The webcamsOnlyForModerator is one example of it: only moderator's camera
+# are going to be shown, that is, if the below property is false.
```
Comment (gustavotrott) [inline record-and-playback/core/scripts/bigbluebutton.yml:46]:
```suggestion
# By default, recordings assume the Viewer viewpoint (with all locks)
# so when webcamsOnlyForModerator=true, only moderators webcams are included in recordings.
# Use this option to ignore locks and assume Moderator viewpoint instead.
```

**Review by gustavotrott — APPROVED** [review]
LGTM!

**Comment by prlanzarin** [comment]
I'm not really apt to say whether this is good to be merged or not. My previous comments were non-blocking clarifications/suggestions.
