### PR TITLE
(Optional) fix(screenshare): change toast notification text

### LINKED ISSUE #14277: Data savings screenshare - inaccurate toast
**Describe the bug**
If data saving (disable screenshare) is enabled during a screenshare, a toast is triggered saying 'Screenshare has ended'. The information is not correct, screenshare is still going on, we just have opted out of viewing it

**To Reproduce**
1. Join a session where screenshare is in progress
2. Go to Settings -> Data savings -> toggle off screenshare viewing
3. Screenshare stops (good). However, some toasts show up

**Expected behavior**
Toast saying "screenshare stopped [because you opted out? / due to data savings]"

**Actual behavior**
Toast says "Screenshare has ended"

**Screenshots**

**BBB version:**
BigBlueButton 2.4.2

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

Changes toast notification text from "Screenshare has stopped" to "Screenshare has stopped due to data saving" whenever screenshare stops due to data savings.

Captura de tela de 2022-02-07 14-30-42
Captura de tela de 2022-02-07 14-30-46

### Closes Issue(s)

Closes #14277

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/screenshare/component.jsx [hunk 1]
```diff
@@ -148,7 +153,11 @@ class ScreenshareComponent extends React.Component {
     window.removeEventListener('screensharePlayFailed', this.handlePlayElementFailed);
     unsubscribeFromStreamStateChange('screenshare', this.onStreamStateChange);
 
-    notify(intl.formatMessage(intlMessages.screenshareEnded), 'info', 'desktop');
+    if (!Settings.dataSaving.viewScreenshare) {
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/screenshare/component.jsx:156]: Let's consider reordering

`if (Settings.dataSaving.viewScreenshare)`
`else`
