### PR TITLE
Fix small bugs on video-provider

### LINKED ISSUE #5305: Sharing webcam in FireFox pops errors while waiting for user permission to share webcam

### LINKED ISSUE #5308: Share webcam button vanishes
Steps to reproduce the error:
1. Open two sessions in html5 client.(one in Firefox, one in Chrome)
2. Share your webcam in one session.
3. Try to share the same webcam in another session.

You should get an error in second session, and after that the share webcam button vanishes.

### PR DESCRIPTION
**Pull request by gutobenn**
- Add box-shadow on video button
- Reenable video button on SFU or permission errors (fixes #5308)
- Wait for user permission before starting timeout (fixes #5305)

### CODE REVIEW

**Comment by Tainan404** [comment]
Box-shadow is being applied to the close button.

review-gutobenn-01

File: bigbluebutton-html5/imports/ui/components/video-provider/video-menu/component.jsx [hunk 1]
```diff
@@ -50,10 +50,12 @@ const JoinVideoOptions = ({
       ));
   return (
     <Dropdown
+      className={styles.container}
       autoFocus
     >
       <DropdownTrigger tabIndex={0}>
         <Button
+          className={styles.button}
```
Comment (Tainan404) [inline bigbluebutton-html5/imports/ui/components/video-provider/video-menu/component.jsx]: have any issues about it? because the button component already removes the outline.

https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/imports/ui/components/button/styles.scss#L84

Comment (gutobenn) [reply bigbluebutton-html5/imports/ui/components/video-provider/video-menu/component.jsx]: Yes, without this the outline is displayed on button focus. I did it based on the audio button. (https://github.com/bigbluebutton/bigbluebutton/blob/v2.0.x-release/bigbluebutton-html5/imports/ui/components/audio/audio-controls/styles.scss#L25)
