### PR TITLE
Validate endpoints and env variables before running all tests

### LINKED ISSUE #23450: Validate `/create` and `/join` endpoints before running all tests
**Describe the test scenario, be specific**
Currently, in case something goes wrong with an API request, the error logged is something like:

Image

To avoid excessive failure logs with no descriptive information:

- Add a check using the global `beforeAll` hook requesting both endpoints. In case the response is not the expected, stop the execution;
- Additionally, validate the env variables (I suggest checking similarly as https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/blob/v0.0.x/tests/core/fixtures/sampleBeforeAll.ts#L22-L25);

### PR DESCRIPTION
**Pull request by pinhaum**
This pull request addresses [issue #23450](https://github.com/bigbluebutton/bigbluebutton/issues/23450) by improving the reliability and clarity of our test suite setup. Specifically, it ensures the /create and /join endpoints, as well as required environment variables, are validated before any tests run. This prevents excessive, unhelpful failure logs when endpoints are unavailable or misconfigured.

### What does this PR do?
- Make initial requests to both /create and /join endpoints.
- If either endpoint does not respond as expected, the test run is aborted early with a clear error message.
- Validates required environment variables at test startup,

### Closes Issue(s)
Closes #23450

### CODE REVIEW

File: bigbluebutton-tests/playwright/fixtures.js [hunk 1]
```diff
@@ -1,8 +1,47 @@
...
 const { fullyParallel } = require('./playwright.config');
+const parameters = require('./core/parameters');
+const helpers = require('./core/helpers');
+
+base.test.beforeAll(async ({ request }) => {
+  // Validate environment variables and endpoints
+  const BBB_URL_PATTERN = /^https:\/\/[^/]+\/bigbluebutton\/(?:api\/?)?$/;
+  if (!parameters.secret) throw new Error('BBB_SECRET environment variable is not set');
+  if (!parameters.server) throw new Error('BBB_URL environment variable is not set');
+  if (!BBB_URL_PATTERN.test(parameters.server)) throw new Error('BBB_URL must follow the pattern "https://{{DOMAIN_NAME}}/bigbluebutton/"');
```
Comment (antonbsa) [inline bigbluebutton-tests/playwright/fixtures.js]:
```suggestion
  if (!BBB_URL_PATTERN.test(parameters.server)) throw new Error('BBB_URL must follow the pattern "https://{{DOMAIN_NAME}}/bigbluebutton/api"');
```

**Review by antonbsa — CHANGES_REQUESTED** [review]

**Review by antonbsa — APPROVED** [review]
LGTM! well done!
