### PR TITLE
Fix client crashing when prensentation isn't converted

### LINKED ISSUE #6998: If the slide does not convert/load, the client may crash
Screenshot from 2019-03-12 10-43-28

### PR DESCRIPTION
**Pull request by Tainan404**
Closes #6998.

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/presentation/component.jsx [hunk 1]
```diff
@@ -143,13 +143,20 @@ class PresentationArea extends Component {
...
-    const originalWidth = currentSlide.calculatedData.width;
-    const originalHeight = currentSlide.calculatedData.height;
+    const { calculatedData } = currentSlide || {};
+    const originalWidth = calculatedData.width;
+    const originalHeight = calculatedData.height;
 
     let adjustedWidth;
     let adjustedHeight;
 
+    if (!originalHeight || !originalHeight) {
```
Comment (jfsiebel) [inline bigbluebutton-html5/imports/ui/components/presentation/component.jsx]: Did you mean `!originalWidth || !originalHeight`?

Comment (Tainan404) [reply bigbluebutton-html5/imports/ui/components/presentation/component.jsx]: Fixed!

**Comment by capilkey** [comment]
Were you able to reproduce this reliably before your changes? I ask because I'm pretty sure the updated code will still throw an exception on line 147 and 148 as they are going to try and lookup properties on an undefined object still.
