### PR TITLE
fix: Close poll on slide change

### LINKED ISSUE #16870: Quick poll -- if you did not submit a vote, hide the dialog on slide change
**Describe the bug**
Quick poll reads a question and some polling options from the slide and polls everyone. However, if someone does not vote, the polling options remains visible forever (including after a slide change)

**To Reproduce**
1. Presenter prepares a presentation with quick poll on page 2
2. Viewer joins
3. Presenter switches to slide 2 and hits the quick poll button
4. Viewer sees the prompt to vote but does not vote
5. Presenter switches to slide 3

**Expected behavior**
Viewer no longer sees the prompt from slide 2

**Actual behavior**
Viewer sees the prompt forever and has no option to hide it. Only option is "Submit" but is grayed out

**Screenshots**
Screenshot from 2023-03-01 16-40-19

**BBB version:**
BigBlueButton 2.6.0-c.5

### PR DESCRIPTION
**Pull request by zhem0004**
### What does this PR do?

Closes poll modal when moderator changes slide

### Closes Issue(s)
Closes #16870

### Motivation

Previously - if the user hasn't answered - the modal would remain open permanently

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx [hunk 1]
```diff
@@ -165,13 +167,15 @@ class PresentationToolbar extends PureComponent {
     } = this.props;
 
     if (event) event.currentTarget.blur();
+    if (currentPoll()) makeCall('stopPoll');
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx:170]: could we define stopPoll in the same context we define `nextSlide` and pick it from props?
This would mean  no need to import makeCall in the component

**Review by antobinary — CHANGES_REQUESTED** [review]

File: bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx [hunk 2]
```diff
@@ -165,13 +165,15 @@ class PresentationToolbar extends PureComponent {
     } = this.props;
 
     if (event) event.currentTarget.blur();
+    this.props.endCurrentPoll();
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/presentation/presentation-toolbar/component.jsx:168]: please  add `endCurrentPoll` to the list of items we get from `this.props` (2 lines above)

**Review by antobinary — CHANGES_REQUESTED** [review]

**Review by antobinary — APPROVED** [review]
LGTM
