### PR TITLE
Fix Presentation uploader missing items

### LINKED ISSUE #12267: Next presenter does not see current popup
**Describe the bug**
When a new presenter is selected, he/she first sees an outdated view when opening the "Manage presentation" popup. Only by closing the popup and reopening it, the current presentation can be seen.

**To Reproduce**
1. Upload any presentation
2. choose a new presenter
3. go to "Manage presentations" with this one
4. you can only see the default.pdf not the new uploaded file

**Expected behavior**
Refresh the popup before open

**Actual behavior**
reloads only after closing (you can see it briefly)

**Screenshots**
image
image

**BBB version (optional):**
BigBlueButton Server 2.3 1669

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser Chrome and Firefox

### PR DESCRIPTION
**Pull request by Tainan404**
### What does this PR do?

This PR fixes the presentaiton uploader not showing new presentations when presenter changes, It happens because theres no logic to update the presentation list in the client of the new presenter.

### Closes Issue(s)
Closes #12267

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx [hunk 1]
```diff
@@ -255,6 +255,15 @@ class PresentationUploader extends Component {
     const { isOpen, presentations: propPresentations } = this.props;
     const { presentations } = this.state;
 
+    if (prevProps.isOpen !== isOpen && isOpen) {
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/presentation/presentation-uploader/component.jsx:258]: How is this different from 

`if (!prevProps.isOpen) {`

**Review by daminebenq — APPROVED** [review]
