### PR TITLE
fix: Keyboard Access To Assign Users To Breakout Room Broken

### LINKED ISSUE #13003: Keyboard Access To Assign Users To Breakout Room Broken
**Describe the bug**
Keyboard access to assign users to breakout room's has been broken by commit:

https://github.com/bigbluebutton/bigbluebutton/commit/145ca61d40e0801a387d35126f755fb96f8b01ad

**To Reproduce**
1. Open Create Breakout Room Modal
2. Navigate to room list via keyboard only

**Expected behavior**
The list should be focusable, up and down arrow keys should cycle the users in the list. left and right arrow keys should move users between room lists.

**Actual behavior**
Room lists are not focusable and the room assignment no longer works.

**BBB version:**
2.4-beta-3

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

Restores keyboard access in breakout room modal.

### Closes Issue(s)
Closes #13003

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx [hunk 1]
```diff
@@ -871,6 +871,7 @@ class BreakoutRoom extends PureComponent {
     return this.getUserByRoom(room)
       .map((user) => (
         <p
+          tabIndex={0}
```
Comment (KDSBrowne) [inline bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx:874]: Setting the `tabIndex`'s to `0` for the names in the list will force a keyboard user into tabbing through each name in a list before being able to move to the next. This can be problematic with  a lot of users in the list. We should set this `tabIndex` to `-1`.

**Review by KDSBrowne — CHANGES_REQUESTED** [review]

**Review by KDSBrowne — APPROVED** [review]
