### PR TITLE
Enforce authToken to re-joining users

### LINKED ISSUE #5261: Reconnecting users do not pass authToken when trying to re-join
I have seen this in the logs on our html5 testing server and added some additional lines of logs (the ones starting with `User=`) in https://github.com/bigbluebutton/bigbluebutton/pull/5258/files

The logs below are from a dev environment - I stopped meteor while I had some users in a meeting. When restarting meteor all of these users were led to logoutUrl with the same serverside error. On the test server (production mode) the process was not restarted so there must be another way to hit the same issue but perhaps solving it on dev environment through restart will resolve it for production too...

```
I20180319-17:38:33.956(0)? info: User 'w_ohr1fejacrav' is trying to validate auth token for meeting '183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1521480451670'
I20180319-17:38:33.996(0)? info: REDIS: {"header":{"name":"ValidateAuthTokenRespMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1521480451670","userId":"w_ohr1fejacrav"},"body":{"userId":"w_ohr1fejacrav","authToken":"0bdgmh5vypjf","valid":true,"waitForApproval":false}} emitted
I20180319-17:38:33.998(0)? info: Updated connectionId user=w_ohr1fejacrav connectionId=v9SLhv65pZkk4J58S meeting=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1521480451670
I20180319-17:38:34.001(0)? info: User= {"_id":"6jkjMNvz9sij6GdEK","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1521480451670","userId":"w_ohr1fejacrav","connectionStatus":"online","roles":["viewer","presenter","moderator"],"sortName":"1html","color":"#263238","intId":"w_ohr1fejacrav","extId":"w_ohr1fejacrav","name":"1html","role":"MODERATOR","guest":false,"authed":false,"waitingForAcceptance":false,"emoji":"none","locked":true,"presenter":true,"avatar":"https://anton3.blindside-dev.com/client/avatar.png","moderator":true,"connectionId":"v9SLhv65pZkk4J58S"}
I20180319-17:38:34.002(0)? info: User='w_ohr1fejacrav' is joining meeting='183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1521480451670' authToken='undefined' pt1
I20180319-17:38:34.003(0)? info: REDIS: ValidateAuthTokenRespMsg: Error: Match error: Expected string, got undefined
I20180319-17:38:34.003(0)?     at exports.check (packages/check.js:55:15)
I20180319-17:38:34.003(0)?     at userJoin (imports/api/users/server/methods/userJoin.js:15:3)
I20180319-17:38:34.004(0)?     at EventEmitter.handleValidateAuthToken (imports/api/users/server/handlers/validateAuthToken.js:57:5)
I20180319-17:38:34.004(0)?     at EventEmitter.emitAsync (/home/ubuntu/dev/bigbluebutton/bigbluebutton-html5/node_modules/eventemitter2/lib/eventemitter2.js:461:31)
I20180319-17:38:34.005(0)?     at MettingMessageQueue.handleTask (imports/startup/server/redis.js:80:10)
I20180319-17:38:34.005(0)?     at PowerQueue.runTask (packages/cfs_power-queue.js:596:14)
I20180319-17:38:34.005(0)?     at PowerQueue.updateThrottleUp (packages/cfs_power-queue.js:402:12)
I20180319-17:38:34.005(0)?     at PowerQueue.next (packages/cfs_power-queue.js:451:10)
I20180319-17:38:34.005(0)?     at PowerQueue._autoStartTasks (packages/cfs_power-queue.js:356:14)
I20180319-17:38:34.006(0)?     at PowerQueue.add (packages/cfs_power-queue.js:381:10)
I20180319-17:38:34.006(0)? info: REDIS: ValidateAuthTokenRespMsg completed sync
I20180319-17:38:34.166(0)? info: User 'w_ohr1fejacrav' is leaving meeting '183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1521480451670'
I20180319-17:38:34.167(0)? info: User 'w_ohr1fejacrav' is leaving meeting '183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1521480451670'
I20180319-17:38:34.170(0)? info: REDIS: {"header":{"name":"UserLeftMeetingEvtMsg","meetingId":"183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1521480451670","userId":"w_ohr1fejacrav"},"body":{"intId":"w_ohr1fejacrav"}} emitted
I20180319-17:38:34.171(0)? info: REDIS: UserLeftMeetingEvtMsg completed sync
I20180319-17:38:34.171(0)? info: Remove voiceUser=w_ohr1fejacrav meeting=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1521480451670
I20180319-17:38:34.172(0)? info: Removed HTML5 user id=w_ohr1fejacrav meeting=183f0bf3a0982a127bdb8161e0c44eb696b3e75c-1521480451670
```

This branch includes #5259

### PR DESCRIPTION
**Pull request by jfsiebel**
Enforce authToken for every user that tries to rejoin a meeting, resolve #5261.

### CODE REVIEW

File: bigbluebutton-html5/imports/api/users/server/modifiers/setConnectionId.js [hunk 1]
```diff
@@ -2,9 +2,10 @@ import { check } from 'meteor/check';
 import Users from '/imports/api/users';
 import Logger from '/imports/startup/server/logger';
 
-export default function setConnectionId(meetingId, userId, connectionId) {
+export default function setConnectionId(meetingId, userId, connectionId, authToken) {
```
Comment (oswaldoacauan) [inline bigbluebutton-html5/imports/api/users/server/modifiers/setConnectionId.js]: This function should only set the connection id. You need to change the function name or create another one for updating the authToken.
