### PR TITLE
tests: Add test for "autohide whiteboard toolbar"

### LINKED ISSUE #23797: test: Auto hide whiteboard toolbar
**Describe the test scenario, be specific**
considering `whiteboardToolbarAutoHide: false` in `https://github.com/bigbluebutton/bigbluebutton/blob/v3.0.x-release/bigbluebutton-html5/private/config/settings.yml#L205`:

Steps to reproduce:
1. Join a session with a user;
2. Go to `Options > Settings`;
3. Enable `Auto Hide Whiteboard Toolbars`;
4. Hover whiteboard - should appear all toolbar items (check with visible element assertion);
5. Hover the cursor out of the whiteboard;
6. Wait a few seconds - the items should disappear (check with snapshot comparison);

### PR DESCRIPTION
**Pull request by pinhaum**
### What does this PR do?
This PR implements test coverage for the auto hide whiteboard toolbar feature in BigBlueButton. The test validates the functionality that allows users to enable/disable automatic hiding of the whiteboard toolbar through the application settings.

#### Changes Made
- Added autoHideWhiteboardToolbar() method in bigbluebutton-tests/playwright/options/options.js
- Added test case "Auto hide whiteboard toolbar" in bigbluebutton-tests/playwright/options/options.spec.js
- Added wbAutoHideToggleBtn selector in bigbluebutton-tests/playwright/core/elements.js

#### Notes
The test addresses the specific scenario mentioned in the issue, considering:
- Default state with whiteboardToolbarAutoHide: false setting
- User interaction to enable the auto-hide feature
- Dynamic toolbar visibility based on mouse position
- Settings persistence after modal confirmation

#### Video example

https://github.com/user-attachments/assets/49825212-9a57-48db-8631-f529fc0be2a2

### Closes Issue(s)
Closes #23797 

### How to test
1. run playwright options tests with:
`npm run test options` or `npx playwright test options`
you can also run the specific test using the command:
`npm run test:filter "Auto hide whiteboard toolbar"`
2. Confirm that the end meeting test passes and UI behaves as expected.

### CODE REVIEW

File: bigbluebutton-tests/playwright/options/options.js [hunk 1]
```diff
@@ -159,6 +159,42 @@ class Options extends MultiUsers {
...
     }
   }
+
+  async autoHideWhiteboardToolbar() {
+    await this.modPage.waitForSelector(e.whiteboard);
+    await this.modPage.hasElement(e.wbToolbar, 'should display the whiteboard toolbar');
+    await this.modPage.closeAllToastNotifications();
+
+    const whiteboardLocator = await this.modPage.getLocator(e.whiteboard);
+    await expect(whiteboardLocator).toHaveScreenshot('whiteboard-with-toolbar-visible.png');
```
Comment (antonbsa) [inline bigbluebutton-tests/playwright/options/options.js:169]: missing description

File: bigbluebutton-tests/playwright/options/options.js [hunk 2]
```diff
@@ -159,6 +159,42 @@ class Options extends MultiUsers {
...
+    await this.modPage.hasElement(e.wbToolbar, 'should display the whiteboard toolbar when hover the whiteboard');
+
+    await this.modPage.hoverElement(e.chatButton)
+
+    const hasFadeOutClass = wbTollbarLocator.evaluate(node =>
+      node.classList.contains('fade-out')
+    );
+    expect(hasFadeOutClass, 'should have fade-out class after hoovering out of the whiteboard').toBeTruthy();
+
+    await expect(whiteboardLocator).toHaveScreenshot('whiteboard-with-toolbar-hidden.png', {
```
Comment (antonbsa) [inline bigbluebutton-tests/playwright/options/options.js:186]: missing description

File: bigbluebutton-tests/playwright/options/options.js [hunk 3]
```diff
@@ -159,6 +159,42 @@ class Options extends MultiUsers {
...
+
+    const whiteboardLocator = await this.modPage.getLocator(e.whiteboard);
+    await expect(whiteboardLocator).toHaveScreenshot('whiteboard-with-toolbar-visible.png');
+
+    await openSettings(this.modPage);
+    await this.modPage.waitAndClickElement(e.wbAutoHideToggleBtn);
+    await this.modPage.hasElementEnabled(e.wbAutoHideToggleBtn, 'should display the auto hide whiteboard toolbar toggle enabled');
+
+    await this.modPage.waitAndClick(e.modalConfirmButton);
+    await sleep(500);
```
Comment (antonbsa) [inline bigbluebutton-tests/playwright/options/options.js]: try to wait for the whiteboard element (with `waitForSelector`) instead of a static timeout to proceed

**Review by antonbsa — CHANGES_REQUESTED** [review]

**Review by antonbsa — APPROVED** [review]
