### PR TITLE
Fix layout broken after open+close shared notes

### LINKED ISSUE #12050: [2.3 Beta 3+] Broken layout after open+close shared notes multiple times
**Describe the bug**
Opening/closing shared notes breaks layout (see screenshot)

**To Reproduce**

1. Join a BBB conference. 
2. Open some cameras (we had 3). Do not change camera/slide size, so that autolayout is active
2. open shared notes
3. close shared notes by clicking on "shared notes" again (neither shared notes nor chat are visible)
4. open shared notes again
5. layout is broken

I know that there were some fixes after 2.3 Beta3, so I tested this on commit (8cd827a379). If you resize the slides, everything is fine again and this bug cannot be triggered anymore.

**Screenshots**
Bildschirmfoto von 2021-04-16 09-09-37

**BBB version (optional):**

BBB 2.3 Beta, commit 8cd827a379

**Desktop (please complete the following information):**
 - OS: Linux
 - Browser: Firefox
 - Version 78.9.0esr

### PR DESCRIPTION
**Pull request by vitormateusalmeida**
This PR closes #12050. 
Added an update after some panel (shared notes and others) is open/close to fix the issue.
Fix some linter errors.

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/poll/component.jsx [hunk 1]
```diff
@@ -212,9 +213,10 @@ class Poll extends Component {
     });
   }
 
-  handleInputChange(index, event) {
-    this.handleInputTextChange(index, event.target.value);
-  }
+  // Duplicated function
+  // handleInputChange(index, event) {
+  //   this.handleInputTextChange(index, event.target.value);
+  // }
```
Comment (ramonlsouza) [inline bigbluebutton-html5/imports/ui/components/poll/component.jsx:219]: could you remove this function instead of comment out?

**Review by ramonlsouza — CHANGES_REQUESTED** [review]
Tested locally, could not reproduce #12050.

Issue #12143 is very similar, but not fixed by this PR

**Review by ramonlsouza — APPROVED** [review]

**Review by daminebenq — APPROVED** [review]
