### PR TITLE
Fix log error when meteor restart

### LINKED ISSUE #6726: Error log when meteor restart
errorlogmeteorrestart

### PR DESCRIPTION
**Pull request by vitormateusalmeida**
Closes #6726

### CODE REVIEW

File: bigbluebutton-html5/imports/startup/client/base.jsx [hunk 1]
```diff
@@ -76,6 +78,11 @@ class Base extends Component {
       Session.set('isMeetingEnded', true);
     }
 
+    // In case the meteor restart avoid error log
+    if (Meteor.status().connected && (prevState.meetingExisted !== meetingExisted)) {
```
Comment (oswaldoacauan) [inline bigbluebutton-html5/imports/startup/client/base.jsx]: `Meteor.status().connected` should come from the container (:
