### PR TITLE
skip share/unshare of flash webcams using "if" instead of "check".

### LINKED ISSUE #5690: Start/stop Flash webcam triggers error on html5 log
`info: REDIS: UserBroadcastCamStartedEvtMsg: Error: Match error: Failed Match.Where validation`

### PR DESCRIPTION
**Pull request by Tainan404**
Closes #5690.

### CODE REVIEW

File: bigbluebutton-html5/imports/api/video/server/handlers/userSharedHtml5Webcam.js [hunk 1]
```diff
@@ -3,17 +3,18 @@ import { check } from 'meteor/check';
 
 export default function handleUserSharedHtml5Webcam({ header, body }, meetingId ) {
   const { userId, stream } = body;
-  const isValidStream = Match.Where((stream) => {
-    check(stream, String);
+  const isValidStream = (match) => {
```
Comment (antobinary) [inline bigbluebutton-html5/imports/api/video/server/handlers/userSharedHtml5Webcam.js]: Please consider changing `match` with `testString` for both `handleUserSharedHtml5Webcam` and `handleUserUnsharedHtml5Webcam`. Otherwise all looks good!
