### PR TITLE
Fix: Pre-defined groups not working when creating Breakout Rooms

### LINKED ISSUE #22046: 3.0: Pre-defined groups not working when creating Breakout Rooms
In BBB 3.0 the pre-defined groups feature is not working.

3.0 (no rooms created automatically in Breakout Rooms):

https://github.com/user-attachments/assets/e46b6a32-c720-4c1d-99ed-f5f45f7f6132

2.7 (rooms created and users assigned):

https://github.com/user-attachments/assets/f08bd039-5067-4d5f-9439-7fad656cfba0

----

The backend seems to be working well as the data of the rooms and its users are alright:

Create Param (Example):
```
groups=[{"id":'1',name:'GroupA',roster:['1235']},{"id":'2',name:'GroupB',roster:['2333','2335']},{"id":'3',roster:[]}]
```

Graphql query:
```gql
query {
  meeting_group {
    groupId
    name
    usersExtId
  }
}
```

Data example:
```json
{
  "data": {
    "meeting_group": [
      {
        "groupId": "1",
        "name": "GroupA",
        "usersExtId": [
          "1235"
        ]
      },
      {
        "groupId": "2",
        "name": "GroupB",
        "usersExtId": [
          "2333",
          "2335"
        ]
      },
      {
        "groupId": "3",
        "name": "",
        "usersExtId": []
      }
    ]
  }
}
```

### PR DESCRIPTION
**Pull request by Tainan404**
### What does this PR do?
Restore the feature of pre-defined groups for breakouts on 3.0

### Closes Issue(s)
Closes #22046

### How to test
Follow the issue steps

### CODE REVIEW

**Review by gabriellpr — APPROVED** [review]

**Comment by gustavotrott** [comment]
It's not working properly in the second time I create breakout rooms. (it should remember the last room of each user).

[Screencast from 2025-02-18 10-30-35.webm](https://github.com/user-attachments/assets/e01cb3b5-98fb-4d84-a9d2-4858166cf80b)



And after all users joined, I can't see the group members properly:

image

**Comment by Tainan404** [comment]
> group members prope


> And after all users joined, I can't see the group members properly:
> 
> image

This Bug isn't related to my PR, I could reproduce on 3.0 dev branch, just asking to join a room 
[Screencast from 18-02-2025 11:38:58.webm](https://github.com/user-attachments/assets/df8b051a-745f-47ab-8337-ba1572e84f66)

**Comment by gustavotrott** [comment]
It's not working when I provide non-numerical IDs for groups:

```
groups=[{"id":'c2djfh',name:'First Group',roster:['1235']},{"id":'bdjeifj',name:'Second Group',roster:['2333','2335']},{"id":'ad33jfj',roster:[]}]
```

image

File: bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/room-managment-state/component.tsx [hunk 1]
```diff
@@ -245,6 +247,39 @@ const RoomManagmentState: React.FC<RoomManagmentStateProps> = ({
...
   }, [users]);
 
+  useEffect(() => {
+    if (groups.length && init && lastBreakoutData && !(lastBreakoutData.breakoutRoom_createdLatest.length > 0)) {
+      const sortedGroups = Array.from(groups).sort((a, b) => {
+        const aId = Number.parseInt(a.groupId, 10);
+        const bId = Number.parseInt(b.groupId, 10);
+
+        return aId - bId;
+      });
```
Comment (gustavotrott) [inline bigbluebutton-html5/imports/ui/components/breakout-room/create-breakout-room/room-managment-state/component.tsx:257]: It shouldn't order by group ID since the ID can be a hash and may not follow a sequence. I added a new field, `groupIndex`, for sorting. I’ve sent the commit to your PR!

image

**Comment by Tainan404** [comment]
> It's not working when I provide non-numerical IDs for groups:
> 
> ```
> groups=[{"id":'c2djfh',name:'First Group',roster:['1235']},{"id":'bdjeifj',name:'Second Group',roster:['2333','2335']},{"id":'ad33jfj',roster:[]}]
> ```
> 
> image

I've fixed that adding the support for `groupIndex.
image
PS: I tested just with one user with extId
