### PR TITLE
fix: Fix whiteboard positioning when switching slides with zoom

### LINKED ISSUE #16285: Whiteboard positioning issue when zooming and switching between presentations
**Describe the bug**
Whiteboard moved up when zooming and then switching to another presentation and back.

**To Reproduce**

1. Upload multiple presentations.

2. Zoom in.
screenshot1

3. Switch to a different presentation, and then switch it back to the initial one.

4. All clients see presentation not zoomed, but the position of it is moved up.
screenshot2

**BBB version:**
2.6.0-beta.4

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Firefox
 - Version: 108.0.1

### PR DESCRIPTION
**Pull request by Tainan404**
### What does this PR do?
the zoom were being set wrong when the presentation changes

### Closes Issue(s)
Closes #16285

https://user-images.githubusercontent.com/15806883/215095014-65202ae9-dc4a-4f5f-b9be-3484c496bd31.mp4

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx [hunk 1]
```diff
@@ -541,7 +541,7 @@ export default function Whiteboard(props) {
   React.useEffect(() => {
     if (isPresenter && slidePosition && tldrawAPI) {
       const zoom = calculateZoom(slidePosition.width, slidePosition.height);
```
Comment (ramonlsouza) [inline bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx:543]:
```suggestion

```

**Review by ramonlsouza — APPROVED** [review]
