### PR TITLE
Fix unread message indicator remains active

### LINKED ISSUE #6624: Unread message indicator remains active for private chats
The unread chat indicator remains active for private chats. Does not affect public chat.

See video below (private chat at aprox 30 seconds)

https://www.youtube.com/watch?v=y6Xs60J29HQ&feature=em-share_video_user

### PR DESCRIPTION
**Pull request by vitormateusalmeida**
Closes #6624

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx [hunk 1]
```diff
@@ -39,17 +37,11 @@ export default withTracker(() => {
...
-    // 2.filter the user except the current user from the user array
-    // 3.add the public chat to the array
-    // 4.check current user has unread messages or not.
-    return users
-      .map(user => user.id)
-      .filter(userID => userID !== Auth.userID)
-      .concat(PUBLIC_GROUP_CHAT_ID)
-      .some(receiverID => ChatService.hasUnreadMessages(receiverID));
+    const activeChats = userListService.getActiveChats();
+    const hasUnreadMessages = activeChats
```
Comment (jfsiebel) [inline bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx]: Why not return the result directly?

Comment (Tainan404) [reply bigbluebutton-html5/imports/ui/components/nav-bar/container.jsx]: IMO, is good as-is, the variable has a meaningful name explaining his content avoiding the next programmer pass function by function to know the content
