### PR TITLE
Fix ActionBar moderator check

### LINKED ISSUE #6565: Non-moderators see error isUserModerator` prop undefined
screenshot from 2019-01-16 11-11-40

Joined a new meeting with a moderator user in one browser and a viewer (non-moderator) in another. The second one sees the error in console. Looks like it happens every time we do not need to render the Actions (+) button

### PR DESCRIPTION
**Pull request by capilkey**
The code was trying to use the `moderator` property of User, but that doesn't exist and the role is actually stored in `role`. This PR fixes #6565.

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/actions-bar/service.js [hunk 1]
```diff
@@ -20,7 +23,7 @@ const takePresenterRole = () => makeCall('assignPresenter', Auth.userID);
 
 export default {
   isUserPresenter: () => Users.findOne({ userId: Auth.userID }).presenter,
-  isUserModerator: () => Users.findOne({ userId: Auth.userID }).moderator,
+  isUserModerator: () => Users.findOne({ userId: Auth.userID }).role === ROLE_MODERATOR,
```
Comment (Tainan404) [inline bigbluebutton-html5/imports/ui/components/actions-bar/service.js]: IMO would be better use the service [mapUser](https://github.com/bigbluebutton/bigbluebutton/blob/master/bigbluebutton-html5/imports/ui/services/user/mapUser.js) that does that work already or add this field in addUser handler, something like  `user.moderator = user.moderator || false`

**Comment by capilkey** [comment]
My goal was to be minimally invasive when solving the issue. When we're
this late in the dev cycle it's safer to not touch a lot of things and
potentially cause more issues.
