### PR TITLE
tests: Add test for drag and drop webcam

### LINKED ISSUE #23873: test: Drag/Drop webcam in a different location
**Describe the test scenario, be specific**
Add tests for Drag/Drop webcam in a different location of the UI

Steps to reproduce:
1. join a session with mod user
2. (mod) share webcam
3. (mod) **assert** webcam is being shared
4. (mod) click on the webcam container and drag to one of the four possible areas for droping the container
5. (mod) **assert** the container is in the right area
6. (mod) **asser** the webcam is still being shared
7. repeat 4-6 until all areas are checked

### PR DESCRIPTION
**Pull request by pinhaum**
### What does this PR do?
This PR adds test coverage for the drag and drop webcam functionality. The tests verify that users can drag webcam containers to different dock areas (top, bottom, left, right, and sidebar bottom) and that the layout updates correctly. Additionally, it updates the existing "update everyone's layout" test to include drag and drop webcam interactions.

#### Changes Made
•  Added new dragAndDropWebcamInDifferentAreas() method in webcam.js that tests dragging webcam containers to all available drop areas
•  Added drag and drop test case in webcam.spec.js 
•  Updated updateEveryone() method in layouts.js to include drag and drop webcam testing for layout synchronization

#### Notes
•  Tests verify that drop areas become visible when starting to drag a webcam container
•  Each drag and drop operation includes visual verification through screenshot comparison
•  Layout synchronization is tested to ensure all participants see webcam position updates when "update everyone's layout" is enabled
•  Tests cover all five available dock areas: top, bottom, left, right, and sidebar bottom
•  Configuration persistence is verified through layout update propagation to all meeting participants

#### Video Example

[drag-drop-webcam.webm](https://github.com/user-attachments/assets/01199212-a44d-4baf-8882-fc61830a7e26)

### Closes Issue(s)
Closes #23873 

### How to Test
1. run playwright webcam tests with:
`npm run test webcam` or `npx playwright test webcam`
you can also run the specific test using the command:
`npm run test:filter "Drag and drop webcam in different areas"`
2. Confirm that the drag and drop test passes and UI behaves as expected.

### CODE REVIEW

File: bigbluebutton-tests/playwright/webcam/webcam.js [hunk 1]
```diff
@@ -184,6 +184,44 @@ class Webcam extends Page {
...
+    await this.hasElement(e.currentUserLocalStreamVideo, 'should display the webcam video after shared');
+
+    await this.getLocator(e.currentUserLocalStreamVideo).hover({ timeout: 5000 });
+    await this.page.mouse.down(); // click on the webcam container
+    await this.hasElement(e.dropAreaRight, 'should display the docking element on the Right area after clicking to drag webcam element');
+    await this.hasElement(e.dropAreaBottom, 'should display the docking element on the Bottom area after clicking to drag webcam element');
+    await this.hasElement(e.dropAreaLeft, 'should display the docking element on the Left area after clicking to drag webcam element');
+    await this.hasElement(e.dropAreaTop, 'should display the docking element on the Top area after clicking to drag webcam element');
+    await this.hasElement(e.dropAreaSidebarBottom, 'should display the docking element on the Sidebar Bottom area after clicking to drag webcam element');
+    await expect(this.page).toHaveScreenshot('drag-drop-areas.png');
```
Comment (antonbsa) [inline bigbluebutton-tests/playwright/webcam/webcam.js]: use `mask` on webcam elements when comparing page snapshots

**Review by antonbsa — CHANGES_REQUESTED** [review]

**Review by antonbsa — APPROVED** [review]
