### PR TITLE
Fix refPresentationContainer requestFullscreen is not a function

### LINKED ISSUE #7279: PresentationContainer requestFullscreen is not a function
```
error: CLIENT LOG: TypeError: this.refPresentationContainer.requestFullscreen is not a function. (In 'this.refPresentationContainer.requestFullscreen()', 'this.refPresentationContainer.requestFullscreen' is undefined)

Apr 18 17:10:25 demo.bigbluebutton.org systemd_start.sh[4082]: n@https://demo.bigbluebutton.org/html5client/09daed9a351ecdcc366b772c255561ee3dc390bd.js?meteor_js_resource=true:125:248354

```

I do not have a visual of what happened

### PR DESCRIPTION
**Pull request by KDSBrowne**
Closes #7279.

Selecting the fullscreen button on the presentation should no longer cause the error to be shown.

In Edge the error was  : `clientLogger: TypeError: Object doesn't support property or method 'requestFullscreen'`.

### CODE REVIEW

**Comment by Tainan404** [comment]
When I join in BBB I'm getting this error.
image

File: bigbluebutton-html5/imports/ui/components/video-provider/fullscreen-button/container.jsx [hunk 1]
```diff
@@ -0,0 +1,12 @@
+import React from 'react';
+import FullscreenButtonComponent from './component';
+import { toggleFullScreen } from '/imports/ui/components/nav-bar/settings-dropdown/service';
+
+const FullscreenButtonContainer = props => <FullscreenButtonComponent {...props} />;
+
+export default (props) => {
+  const handleToggleFullScreen = ref => toggleFullScreen(ref);
+  return (
+    <FullscreenButtonContainer {...props} {...{ handleToggleFullScreen }} />
```
Comment (Tainan404) [inline bigbluebutton-html5/imports/ui/components/video-provider/fullscreen-button/container.jsx]:
```suggestion
    <FullscreenButtonContainer  { ...props, ...{ handleToggleFullScreen }} />
```

Comment (KDSBrowne) [reply bigbluebutton-html5/imports/ui/components/video-provider/fullscreen-button/container.jsx]: This seems to cause a syntax error.
image
