### PR TITLE
Fix for the client logging error

### LINKED ISSUE #5920: Undefined values in logClient
` Exception while invoking method 'logClient' TypeError: Cannot read property 'meetingId' of undefined`
`Exception while invoking method 'logClient' TypeError: Cannot set property 'validUser' of undefined`
...
at DDPCommon.MethodInvocation.logClient (imports/api/log-client/server/methods/logClient.js:10:36)

### PR DESCRIPTION
**Pull request by MaximKhlobystov**
Fixes #5920.

### CODE REVIEW

File: bigbluebutton-html5/imports/api/log-client/server/methods/logClient.js [hunk 1]
```diff
@@ -1,19 +1,19 @@
...
+const logClient = function (type, log, fullInfo) {
   const SERVER_CONN_ID = this.connection.id;
   const User = Users.findOne({ connectionId: SERVER_CONN_ID });
-  const logContents = { ...args };
+  const logContents = { fullInfo };
 
   if (User) {
-    if (User.meetingId === args[0].meetingId) {
-      args[0].validUser = 'vaild';
+    if (User.meetingId === fullInfo.meetingId) {
```
Comment (antobinary) [inline bigbluebutton-html5/imports/api/log-client/server/methods/logClient.js]: I keep getting my user as `invalid` - debugging a bit shows `fullInfo.meetingId` as undefined but `fullInfo.credentials.meetingId` as the right one. Please double check
