### PR TITLE
fix(breakout) - Fix inconsistent behavior of create breakout rooms button

### LINKED ISSUE #15756: "Create breakout rooms" button is being hidden and shown wrongly
**Describe the bug**
After creating the breakout rooms, the `Create breakout room` button should not be displayed - the same way as it should reappears after its ending, but it's just getting a different state after clicking the user list toggle button.

**To Reproduce**
1. Join the meeting;
2. Manage users > Create breakout rooms;
3. Confirm the modal;
4. See that the button is still in the manage users' items;
5. Toggle user list;
6. See that now the button isn't there;
7. End the rooms;
8. See that there's no button to create the rooms
9. If you don't toggle the user list, you won't be able to create new rooms;

**Video**

https://user-images.githubusercontent.com/56703993/193120979-6101030d-6aef-48bc-bf02-8d09302a1ac6.mp4

### PR DESCRIPTION
**Pull request by GuiLeme**
### What does this PR do?

It fixes this random behavior of the create breakout rooms button.

https://user-images.githubusercontent.com/69865537/212393846-31826a19-80a5-461f-adaf-9464679ba27c.mp4

### Closes Issue(s)

Closes #15756 #16118

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/container.jsx [hunk 1]
```diff
@@ -54,10 +60,8 @@ const UserOptionsContainer = withTracker((props) => {
     const { name } = meetingProp;
     return name;
   };
-
-  const isRTL = layoutSelect((i) => i.isRTL);
-
   return {
+    ...props,
```
Comment (ramonlsouza) [inline bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-options/container.jsx:64]:
```suggestion
```

**Review by ramonlsouza — APPROVED** [review]
