### PR TITLE
fix: webcam plugin helper overlaps menu

### LINKED ISSUE #115: Camera button area renders over camera chevron in small screens
As you can see the icon is rendered over/below the option chevron for the camera when the component is too small. It seems like all the elements get moved into the chevron area, so maybe the plugin area should be moved there.

**To Reproduce**

1. Share one or more cameras
2. Resize the conference window and change the layout to force a small camera area (the setup from the screenshot can be achieved by squeezing the window horizontally and moving the cameras to the left/right docking spot)
3. With cameras rendered small enough the problem should be visible

**Expected behavior**
Either the icon area should be moved next to the chevron or somehow inside the element accessible via the chevron

**Actual behavior**
Icons render over/below each other

**Screenshots**
Selection_999(424)

**BBB version, plugin in which The bug happened and SDK version:**

3.0 from git 

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser: Firefox 113.02

### PR DESCRIPTION
**Pull request by GuiLeme**
### What does this PR do?

- Fixes the webcam plugin helper overlapping the webcam's menu;
- Fixes an issue where webcam layout breaks when multiple plugin helpers are registered;

### Closes Issue(s)

Closes https://github.com/bigbluebutton/bigbluebutton-html-plugin-sdk/issues/115

### How to test
I'd recommend testing it with the sample `samples/sample-user-camera-helper-plugin` with a bit of changing:

Just add the following extensible-areas to the code like:

```
       new UserCameraHelperButton({
        icon: 'user',
        disabled: false,
        label: 'Second button that will log on the console',
        tooltip: 'this is a button injected by plugin',
        position: UserCameraHelperItemPosition.BOTTOM_LEFT,
        onClick: ({ browserClickEvent }) => {
          pluginLogger.info('Logging from the user camera extensible area', browserClickEvent.clientX);
        },
        displayFunction: ({ userId }) => randomElement?.user.userId === userId,
      }),
      new UserCameraHelperButton({
        icon: 'application',
        disabled: false,
        label: 'Third button that will log on the console',
        tooltip: 'this is a button injected by plugin',
        position: UserCameraHelperItemPosition.BOTTOM_LEFT,
        onClick: ({ browserClickEvent }) => {
          pluginLogger.info('Logging from the user camera extensible area', browserClickEvent.clientX);
        },
        displayFunction: ({ userId }) => randomElement?.user.userId === userId,
      }),
      new UserCameraHelperButton({
        icon: 'group_chat',
        disabled: false,
        label: 'Fourth button that will log on the console',
        tooltip: 'this is a button injected by plugin',
        position: UserCameraHelperItemPosition.BOTTOM_LEFT,
        onClick: ({ browserClickEvent }) => {
          pluginLogger.info('Logging from the user camera extensible area', browserClickEvent.clientX);
        },
        displayFunction: ({ userId }) => randomElement?.user.userId === userId,
      }),
```

These lines of code will have the result you'll see in the next section.

### More

The current behaviour is:

- The official camera menu cannot be in the same corner as the plugin helper extensible areas, they will be in opposite sides (even if the developer explicitly tells it to be in the same corner - Of course these doesn't apply to helpers set in places that doesn't contain the official BBB menu);
- If the camera is not squeezed the maximum plugin helper per corner is 3, beyond that number, a button with 3 dots will appear and the rest of plugin helpers will be there;
- These behaviours work independently.

See demo bellow:

https://github.com/user-attachments/assets/6186b8b5-c355-4862-8b1c-881df3c0e8af

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/plugin-menu-actions/component.tsx [hunk 1]
```diff
@@ -0,0 +1,91 @@
...
+            hideLabel
+            size="sm"
+          />
+        )}
+        opts={{
+          id: `webcam-${userId}-dropdown-menu`,
+          keepMounted: true,
+          transitionDuration: 0,
+          elevation: 3,
+          getcontentanchorel: null,
```
Comment (JoVictorNunes) [inline bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/plugin-menu-actions/component.tsx]:
```suggestion
          getContentAnchorEl: null,
```

**Review by JoVictorNunes — CHANGES_REQUESTED** [review]

**Review by JoVictorNunes — APPROVED** [review]
Just tested it locally. LGTM!

**Comment by JoVictorNunes** [comment]
I see some testing is failing. Let's hold on for a moment.

**Review by JoVictorNunes — APPROVED** [review]
🚀
