### PR TITLE
fix(client): Connection status function accepting 2 params, meant to improve log readability

### LINKED ISSUE #22065: Tweak RTT logging
**Describe the bug**

Image

The logs about RTT are confusing

What is the meaning of the request changing to true/false? Do we need to log this?

On the screenshot 1) and 2) claim that 1600ms are different levels - is it danger or critical?
3) has a normal level logged as a warning  while it's 1) that should have been a warning.

Warning level should only contain things like
rtt worsened to level danger or critical (y ms)
rtt recovered to x ms

**BBB version:**
BigBlueButton 3.0.0-rc.1

### PR DESCRIPTION
**Pull request by Tainan404**
### What does this PR do?
This PR improves RTT logs by combining the setRttValue and setRttStatus functions into one. Previously, misunderstandings arose because these values could become unsynchronized. By consolidating both setters, we ensure that the logs always use the most up-to-date data, thereby displaying the correct values. 

### Closes Issue(s)
Closes #22065

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts [hunk 1]
```diff
@@ -233,4 +244,8 @@ class ConnectionStatus {
   }
 }
 
-export default new ConnectionStatus();
+const connectionsStatusSingleton = new ConnectionStatus();
+
+window.teste = connectionsStatusSingleton;
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts:249]:
```suggestion
```

Let's revert this portion @Tainan404 -- seems you edited the file just to be able to test

**Review by antobinary — CHANGES_REQUESTED** [review]

File: bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts [hunk 2]
```diff
@@ -233,4 +246,8 @@ class ConnectionStatus {
...
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts:251]:
```suggestion
```

**Review by antobinary — APPROVED** [review]
Tested, works well!

File: bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts [hunk 3]
```diff
@@ -233,4 +246,7 @@ class ConnectionStatus {
   }
 }
 
-export default new ConnectionStatus();
+const connectionsStatusSingleton = new ConnectionStatus();
+
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/core/graphql/singletons/connectionStatus.ts:250]:
```suggestion
```
