### PR TITLE
Reduce component re-render on containers that use usersContext

### LINKED ISSUE #12042: Status change forces all the client to render
**Describe the bug**
When the user sets his/her status the data change is triggering multiple parts of the client to render.

**To Reproduce**
1. Enable component update highlighting at react-dev-tools 
2. Change your status

**Expected behavior**
Only the visible components that use the status data to update.

**Actual behavior**
Whole client rendering.

**Screenshots**
Peek 2021-04-15 15-12

**BBB version (optional):**
BigBlueButton Server 2.3

**Desktop (please complete the following information):**
 - OS: Any
 - Browser Any

**Additional context**
There is a lack of caution over this tracker https://github.com/bigbluebutton/bigbluebutton/blob/477d7d5d376461495a32ff68c0232df73c09d1fc/bigbluebutton-html5/imports/ui/components/app/container.jsx#L108-L128

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

Removes unused information from places where users object is passed down from container to component, preventing extra renders when unused fields of Users collection is changed.

#### Additional information

Some renders will only happen in the container, and will not trigger DOM renders

### Closes Issue(s)
Closes #12042

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx [hunk 1]
```diff
@@ -21,7 +21,9 @@ import MediaService, {
 const ActionsBarContainer = (props) => {
   const usingUsersContext = useContext(UsersContext);
   const { users } = usingUsersContext;
-  const currentUser = users[Auth.meetingID][Auth.userID];
+
+  const currentUser = { userId: Auth.meetingID, emoji: users[Auth.meetingID][Auth.userID].emoji };
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/actions-bar/container.jsx:25]:
```suggestion
  const currentUser = { userId: Auth.userID, emoji: users[Auth.meetingID][Auth.userID].emoji };
```

File: bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx [hunk 2]
```diff
@@ -12,9 +12,14 @@ const CLOSED_CHAT_LIST_KEY = 'closedChatList';
 const UserContentContainer = (props) => {
   const usingUsersContext = useContext(UsersContext);
   const { users } = usingUsersContext;
-  const currentUser = users[Auth.meetingID][Auth.userID];
+  const currentUser = {
+    userId: Auth.meetingID,
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/user-list/user-list-content/container.jsx:16]:
```suggestion
    userId: Auth.userID,
```

**Review by daminebenq — APPROVED** [review]
Working as expected. Nothing got broken using this PR.
