### PR TITLE
fix(bbb-export-annotations): Handle text rendering issue

### LINKED ISSUE #20690: Issue in transferring whiteboard data from group session to main session.
I found an issue in transferring whiteboard data from group session to main session. Here's how I tested it: one moderator and one viewer joined a meeting. The moderator created a group session (selected the checkbox to transfer whiteboard from the group session to the main session). The viewer joined the group session. The viewer wrote something using pen. The moderator joined the group session. The viewer made the multi-user-whiteboard option active. The moderator typed something using the whiteboard text-label thing. The moderator ended the group session. The presentation from the group session was transferred to the main session, but it didn't include everything that was written in the group session.

**Expected behavior**
Everything that was written in the whiteboard in the group session should be transferred to the main session.

**Actual behavior**
Not everything that was written in the whiteboard in the group session should be transferred to the main session. Some things were missing, in this case, whatever the meeting moderator typed.

**Screenshots**
Whiteboard in the group session
Screenshot 2024-07-11 at 17 19 52

Transferred PDF to the main session 
Screenshot 2024-07-11 at 17 20 10

**Desktop (please complete the following information):**
 - OS: MacOS 14.4.1 (tried in Windows 11 as well, same result)
 - Browser : Firefox (tried in Chrome as well, same result)
 - Version: 127.0

BigBlueButton Version : 2.7.9

**Screen-recording**

https://drive.google.com/file/d/1GaNnJ-QefJt5_X-J6PHYO0tEowXaKIBl/view?usp=share_link

### PR DESCRIPTION
**Pull request by danielpetri1**
### What does this PR do?
If ImageMagick fails to rasterize text for some reason so that it can be included in a PDF export, a corrupted image file was being generated that prevented subsequent shapes from appearing on the resulting PDF.

This PR proactively prevents the corrupted image file from being included in the SVG.

### Closes Issue(s)
Closes #20690

### How to test
I managed to reproduce the issue by adding very large amounts of text to the whiteboard (e.g., a 5000-word Lorem Ipsum).

### More
In BBB 3.0, we do not rely on ImageMagick to embed text in the exported PDF. Hence, it is not necessary to port this PR.

### CODE REVIEW

File: bbb-export-annotations/workers/process.js [hunk 1]
```diff
@@ -719,20 +725,22 @@ function overlay_text(svg, annotation) {
...
+      transform: `rotate(${rotation} ${rotation_x} ${rotation_y})`,
+    }).ele('image', {
+      'x': textBox_x,
+      'y': textBox_y,
+      'width': textBoxWidth,
+      'height': textBoxHeight,
+      'xlink:href': `file://${dropbox}/text${id}.png`,
+    }).up();
+  }
 }
```
Comment (antobinary) [inline bbb-export-annotations/workers/process.js:744]:
```suggestion
} else {
  logger.warn("Could not render status in render_textbox for JSON.stringify(annotation)");
}
```

File: bbb-export-annotations/workers/process.js [hunk 2]
```diff
@@ -651,25 +655,27 @@ function overlay_sticky(svg, annotation) {
...
+    }).up()
+        .ele('image', {
+          'x': textBox_x,
+          'y': textBox_y,
+          'width': textBoxWidth,
+          'height': textBoxHeight,
+          'xlink:href': `file://${dropbox}/text${id}.png`,
+        }).up();
+  }
 }
```
Comment (antobinary) [inline bbb-export-annotations/workers/process.js:679]:
```suggestion
} else {
  logger.warn("Could not render status in overlay_sticky for JSON.stringify(annotation)");
}
```

File: bbb-export-annotations/workers/process.js [hunk 3]
```diff
@@ -607,10 +611,10 @@ function overlay_shape_label(svg, annotation) {
   const label_center_x = shape_x + shape_width * x_offset;
   const label_center_y = shape_y + shape_height * y_offset;
 
-  render_textbox(fontColor, font, fontSize, textAlign, text, id);
+  const renderStatus = render_textbox(fontColor, font, fontSize, textAlign, text, id);
   const shape_label = path.join(dropbox, `text${id}.png`);
 
-  if (fs.existsSync(shape_label)) {
+  if (fs.existsSync(shape_label) && renderStatus) {
```
Comment (antobinary) [inline bbb-export-annotations/workers/process.js:617]: Please add an `else` with some warning.

**Comment by antobinary** [comment]
>Notice:   1 failed
>    [Chromium] › presentation/presentation.spec.js:95:5 › Presentation › Manage › Send presentation in the current state (with annotations) to chat for downloading @ci

I am pulling the code locally to do some testing. The webcam/screenshots from CI don't seem to show anything useful on this one. I guess it's the lack of the result that is being demonstrated.

**Review by antobinary — APPROVED** [review]
