### PR TITLE
Recording: avoid short cuts in audio processing

### LINKED ISSUE #24631: Recording playback of some meetings hangs (LiveKit audio)
**Describe the bug**
A customers recording can't get processed correctly because the ffmpeg command fails.
Log: https://pastebin.think-modular.com/upload/emu-lizard-camel
At the end of the log file you will find:
```
I, [2026-02-09T15:26:25.754910 #888229]  INFO -- : Executing: ffmpeg -y -v warning -nostats -max_error_rate 1.0 -copyts -f nut -i pipe:5 -filter_complex_script /var/bigbluebutton/recording/process/presentation/7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-1xxxxxxxxxxxxx/deskshare_1.mp4.filter -an -codec libx264 -threads 2 -preset faster -tune film -x264opts subme\=2:bframes\=5:stitchable\=1 -crf 23 -force_key_frames expr:gte\(t,n_forced\*10\) -pix_fmt yuv420p -r 5 /var/bigbluebutton/recording/process/presentation/7xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx-1xxxxxxxxxxxxx/deskshare_1.mp4
I, [2026-02-09T15:26:29.079607 #888229]  INFO -- : ffmpeg command pid 888231 exit 0 (deskshare_1.mp4.log)
D, [2026-02-09T15:26:29.091831 #888229] DEBUG -- : video source command pid 888230 exit 255 (ffmpeg-preprocess-1042989_deskshare_x0_y0.log)
D, [2026-02-09T15:26:29.091940 #888229] DEBUG -- : av_interleaved_write_frame(): Broken pipe
D, [2026-02-09T15:26:29.091952 #888229] DEBUG -- : Error writing trailer of pipe:6: Broken pipe
```
multiple times.

**To Reproduce**
1. Open recording in browser (~2h long)
2. Watch recording until a specific deskshare was started, then it just stops and loads forever. Skipping forward doesn't work
3. Try to rebuild it
4. ffmpeg throws errors inside log.

**Expected behavior**
Recording should process without issues

**Actual behavior**
Recording stops at around 28 minutes

**Desktop (please complete the following information):**
 - OS: [e.g. Windows, Mac]
 - Browser [e.g. Chrome, Safari]

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]

**Additional context**
This is the first time I've ever experienced this error, and we have thousands of recordings.

### PR DESCRIPTION
**Pull request by kepstin**
With LiveKit audio, it's possible for events for multiple audio start or stop to happen at the same time or very close together, which can result in problems in the audio processing. In particular, having a 0-length segment can result in the final audio track being truncated, resulting in missing audio and other playback issues.

The code being added to audio processing here is based on code which solves a similar problem in video processing: https://github.com/bigbluebutton/bigbluebutton/blob/4c896a7559e1528c3f574f76f77e85d71678a634/record-and-playback/core/lib/recordandplayback/edl/video.rb#L195-L196

This fix is complementary to the changes in https://github.com/bigbluebutton/bigbluebutton/pull/24481 (both can be merged separately, conflicts are minimal/trivial).

Fixes https://github.com/bigbluebutton/bigbluebutton/issues/24631

### CODE REVIEW

File: record-and-playback/core/lib/recordandplayback/edl/audio.rb [hunk 1]
```diff
@@ -43,6 +44,49 @@ def self.dump(edl)
...
       end
 
+      # Edit the EDL to make sure that every cut has a minimum length
+      def self.enforce_cut_lengths(edl)
+        # Special case handling for the start
+        # If there's a cut immediately after the start, the later logic would delete the first cut,
+        # which would result in desync. Any cuts within MIN_CUT_LENGTH of the start have to be
+        # pushed back to avoid this situation. If multiple cuts are pushed back (they'd all get set
+        #  to the same timestamp), the later logic will clean them up.
+        1.upto(edl.length - 1).each do |i|
```
Comment (germanocaumo) [inline record-and-playback/core/lib/recordandplayback/edl/audio.rb:54]:
```suggestion
        1.upto(edl.length - 1).take_while { |i| edl[i][:timestamp] < MIN_CUT_LENGTH }.each do |i|
```
Suggestion from SonarCloud fix to remove .each with break

**Review by germanocaumo — APPROVED** [review]
Looks good

**Review by prlanzarin — APPROVED** [review]
