### PR TITLE
fix: allowModsToUnmuteUsers param not working

### LINKED ISSUE #20879: `allowModsToUnmuteUsers` param not working
**To Reproduce**
1. Create a meeting with `allowModsToUnmuteUsers=true` param;
2. Join a mod and an attendee;
3. Join audio with attendee;
4. Attendee mutes itself;
5. Mod click on the user item in the user list;
6. Show display "Unmute user" button;

**More**
Working properly on v2.7

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

restores missing `muted` field in userlist query, used by unmute user feature.

### Closes Issue(s)
Closes #20879

### How to test
1. Create a meeting with `allowModsToUnmuteUsers=true` param;
2. Join a mod and an attendee;
3. Join audio with attendee;
4. Attendee mutes itself;
5. Mod click on the user item in the user list;
6. Should display "Unmute user" button;

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/core/graphql/queries/users.ts [hunk 1]
```diff
@@ -38,6 +38,7 @@ subscription UserListSubscription($offset: Int!, $limit: Int!) {
       joined
       listenOnly
       voiceUserId
+      muted
```
Comment (gustavotrott) [inline bigbluebutton-html5/imports/ui/core/graphql/queries/users.ts:41]: This prop was removed on purpose!
The idea is reduce the traffic flow of this subscription every time someone mute/unmute.

Look at https://github.com/bigbluebutton/bigbluebutton/pull/20618 to see the new way to get mute/unmute status.

**Review by antonbsa — APPROVED** [review]
