### PR TITLE
fix: Viewer gets blank presentation after minimize/restore

### LINKED ISSUE #18039: [2.6.8] Viewer gets blank presentation after minimize/restore
**Describe the bug**
When a viewer minimizes and restores the presentation, a blank page is displayed instead of the current slide.

**To Reproduce**

1. Start a meeting with a moderator/presenter and a viewer.
2. The viewer minimizes the presentation and restores it (even the default.pdf)
3. The presentation area is blank

**Expected behavior**
When restoring the presentation area, the current slide should be displayed.

**Actual behavior**
The presentation area is blank until the presenter switches to the next slide.

**Screenshots**
Screenshot 2023-05-26 160956

**BBB version:**
BigBlueButton Version: 2.6.8
Clientversion: 623

**Desktop:**
OS: Windows 10
Browser: Any

**Additional context**
The problem does not occur for the presenter. 
We use hidePresentationOnJoin = true. But I don't think that makes any difference.

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

fix blank presentation after minimizing.

### Closes Issue(s)
Closes #18039

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx [hunk 1]
```diff
@@ -956,7 +956,11 @@ export default function Whiteboard(props) {
 
   if (currentTool && !isPanning && !tldrawAPI?.isForcePanning) tldrawAPI?.selectTool(currentTool);
 
-  if (backgroundShape?.src && backgroundShape?.complete && backgroundShape?.src !== bgShape?.src) {
+  if (backgroundShape?.src // if there is a background image
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx:959]:
```
  if (backgroundShape?.src // if there is a background image
```

Technically we checked for `backgroundShape?` already and could remove the next 3 checks for the same. If you'd like to make sure we never drop the `?` we could even do it as:

`if ( backgroundShape && backgroundShape.src // if there is a background image` and then drop the `?` from next 3 lines

**Review by antobinary — APPROVED** [review]
LGTM

**Review by antonbsa — APPROVED** [review]
I just tested in many scenarios and could not see the bug anymore, working as expected!
