### PR TITLE
fix(bbb-web): Improve quality of PNG to SVG conversion

### LINKED ISSUE #21798: PDF rendering error
I installed version 3 of bbb and when I did some tests I saw that it did not render a pdf well, this same pdf renders well in version 2.7
bbb 2.7.15
BBB-2 7-Captura de pantalla 2024-11-28 122035
bbb.3.0.0-beta.5 (1858)
BBB-3Captura de pantalla 2024-11-28 122035

Thank you for your work

### LINKED ISSUE #21821: Fallback to rasterized SVG problematic on BBB 3.0
**Describe the bug**
We see reports that on BBB 3.0.0-beta.5 (and previous) certain slides are not displaying correctly.
Example 1: https://github.com/bigbluebutton/bigbluebutton/issues/21798
Example 2: 
[2.slide.pptx](https://github.com/user-attachments/files/18011002/2.slide.pptx)

2.7:
Screenshot from 2024-12-04 11-47-56

3.0
image

In Example 1 we are seeing path objects threshold exceeded. In Example 2 we see

```
2024-12-04T15:31:11.154Z INFO  o.b.p.imp.SvgImageCreatorImp - Font Type 3 identified on 2.slide.pptx page 1, slide will be rasterized.
2024-12-04T15:31:11.164Z INFO  o.b.p.imp.SvgImageCreatorImp - Font Type 3 identified on 2.slide.pptx page 2, slide will be rasterized.
```
which also leads to rasterizing https://github.com/bigbluebutton/bigbluebutton/blob/v3.0.x-release/bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java#L136-L138

and eventually we hit the PNG -> SVG conversion https://github.com/bigbluebutton/bigbluebutton/blob/v3.0.x-release/bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java#L239

However, it looks the version of ImageMagick we use on BBB 3.0 is behaving differently - https://github.com/bigbluebutton/bigbluebutton/issues/21798#issuecomment-2517690968

---

Option A) - get ImageMagick/another tool to be able to do the conversion.
Option B) - we could try to use the PNG and use it in the client/learning dashboard/recordings and get rid of the SVG code unless it has use for some cases. Still clarifying that part.

Related:
Diagram of steps of conversion: https://docs.bigbluebutton.org/assets/images/presentation-conversion-diagram-svg-conversion-flow-d20e04f3ab62fe7d4a73b5d3ad0e8086.png

cc reporters @jorgelondo for Example 1 and @soheb-somani for Example 2

### PR DESCRIPTION
**Pull request by paultrudel**
### What does this PR do?
When the SVG generated for an uploaded presentation is too complex BBB will fallback to rasterizing the image by converting it a PNG with limited resolution and then converting that PNG to an SVG that will be used by other BBB components. ImageMagick was being used for the PNG to SVG conversion but was leading to poor quality SVGs. The PNG data is now encoded in Base64 and then embedded in an SVG. The limitations with doing this is that a SVG's data URI can only contain  around 2MB of data on most browsers. Therefore, a PNG larger than ~1.5MB will not be able to be embedded in this way due to the larger size from the Base64 encoding overhead.

### Closes Issue(s)
Closes #21798
Closes #21821

### CODE REVIEW

**Comment by gustavotrott** [comment]
Working properly even in Learning Dashboard and Recordings!

<table>

<tr><td>

image

</td></tr>
<tr><td>

image

</td></tr>

File: bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java [hunk 1]
```diff
@@ -236,33 +236,39 @@ private boolean generateSvgImage(File imagePresentationDir, UploadedPresentation
...
-                    if (!errorOutput.isEmpty()) {
-                        log.error("Error during conversion from PNG to SVG: " + errorOutput);
+                try  {
+                    byte[] pngData = readFileToByteArray(tempPng);
+                    String base64encodedPng = Base64.getEncoder().encodeToString(pngData);
+
+                    int binarySize = pngData.length;
+                    int base64Size = base64encodedPng.getBytes(StandardCharsets.UTF_8).length;
+
+                    log.info("PNG size: {} bytes, PNG size after encoding: {} bytes", binarySize, base64Size);
```
Comment (gustavotrott) [inline bbb-common-web/src/main/java/org/bigbluebutton/presentation/imp/SvgImageCreatorImp.java:246]:
```suggestion
```

This log is not necessary IMO.

**Comment by gustavotrott** [comment]
`The limitations with doing this is that a SVG's data URI can only contain around 2MB of data on most browsers.`

Can you send more details about this limitation?

I tried a 7mb-svg with png embedded and it worked fine in Chrome, Brave and Firefox.

image

**Review by gustavotrott — APPROVED** [review]
LGTM! Good job @paultrudel!
