### PR TITLE
Fix cannot read property 'focus' of null

### LINKED ISSUE #7725: Error: Cannot read property 'focus' of null
`{"name":"clientLogger","level":50,"logCode":"startup_error","stackTrace":"TypeError: Cannot read property 'focus' of nulln    at checkTextAreaFocus (https://demo.bigbluebutton.org/html5client/bb4800fb2ac5667db5eedaa4af12024f7cab8a1c.js?meteor_js_resource=true:125:539484)n    at c.handleTouchStart (https://demo.bigbluebutton.org/html5client/bb4800fb2ac5667db5eedaa4af12024f7cab8a1c.js?meteor_js_resource=true:125:539724)n    at Object.u (https://demo.bigbluebutton.org/html5client/bb4800fb2ac5667db5eedaa4af12024f7cab8a1c.js?meteor_js_resource=true:9:24939)n    at h (https://demo.bigbluebutton.org/html5client/bb4800fb2ac5667db5eedaa4af12024f7cab8a1c.js?meteor_js_resource=true:9:25094)n    at m 
`
The logs point to 

`
componentWillUnmount(){window.removeEventListener("beforeunload",this.sendLastMessage),this.sendLastMessage()}checkTextAreaFocus(){const{getCurrentShapeId:e}=this.props.actions,t=document.getElementById(e());return document.activeElement===t||(t.focus(),!1)}handleTouchStart(e){if(this.hasBeenTouchedRecently=!0,setTimeout(()=>{
`

### PR DESCRIPTION
**Pull request by KDSBrowne**
Closes #7725

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx [hunk 1]
```diff
@@ -379,23 +397,28 @@ export default class TextDrawListener extends Component {
...
+    } = this.state;
+    const { actions } = this.props;
+    const { contextMenuHandler } = actions;
     const baseName = Meteor.settings.public.app.cdn + Meteor.settings.public.app.basename;
     const textDrawStyle = {
       width: '100%',
       height: '100%',
       touchAction: 'none',
-      zIndex: 2 ** 31 - 1, // maximun value of z-index to prevent other things from overlapping
+      zIndex: MAX_Z_INDEX, // maximun value of z-index to prevent other things from overlapping
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx]:
```suggestion
      zIndex: MAX_Z_INDEX,
```

File: bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx [hunk 2]
```diff
@@ -5,6 +5,7 @@ const ANNOTATION_CONFIG = Meteor.settings.public.whiteboard.annotations;
 const DRAW_START = ANNOTATION_CONFIG.status.start;
 const DRAW_UPDATE = ANNOTATION_CONFIG.status.update;
 const DRAW_END = ANNOTATION_CONFIG.status.end;
+const MAX_Z_INDEX = 2147483647;
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/whiteboard/whiteboard-overlay/text-draw-listener/component.jsx]:
```suggestion
const MAX_Z_INDEX = 2 ** 31 - 1; // maximum value of z-index to prevent other things from overlapping
```
