### PR TITLE
Fix chat save feature on Firefox

### LINKED ISSUE #6397: Save chat broken on FireFox
The feature Save Chat works well on Chrome (initiates the download of a file containing the public chat) but does not trigger anything in FireFox

### PR DESCRIPTION
**Pull request by BobakOftadeh**
Closes #6397.

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx [hunk 1]
```diff
@@ -97,7 +97,7 @@ class ChatDropdown extends PureComponent {
             `data: ${mimeType} ;charset=utf-8,
             ${encodeURIComponent(ChatService.exportChat(ChatService.getPublicGroupMessages()))}`,
           );
-          link.click();
+          link.dispatchEvent(new MouseEvent('click', { bubbles: true, cancelable: true, view: window }));
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx]: Does this work on Chrome too, Safari, Edge, mobile*?
I thought there would be some browser checking condition in the solution. Would be glad if it's all standard now :)

Comment (antobinary) [reply bigbluebutton-html5/imports/ui/components/chat/chat-dropdown/component.jsx]: https://javascript.info/dispatch-events#event-constructor
screenshot from 2019-02-15 10-31-55
