### PR TITLE
[3.0] fix(layout): ensure the camera position is not undefined

### LINKED ISSUE #23398: Presentation and webcam dock misaligned after switching from smart to custom layout
**Describe the bug**
When switching from the smart layout to the custom layout, clients without a pre-defined local custom layout configuration experience a misplacement of the presentation and camera dock. This results in visual overlap or disappearance of the presentation.

**To Reproduce**
1. Join a meeting with a first user
2. Share webcam
3. Set layout to "smart" and propagate it
4. Join the same meeting with a second user
5. On this user's session, switch to "custom" layout
6. See error

**Expected behavior**
Presentation and webcam dock should render in their designated positions, preserving visibility and preventing overlap.

**Actual behavior**
The presentation overlaps the camera dock, and sometimes the presentation vanishes completely.

**Screenshots**
Image

**BBB version:**
dev30
dev31

**Additional context**
This likely occurs due to the absence of an initialized customLayout in the second user's session and may affect transitions between other layouts, not just from smart to custom.

### PR DESCRIPTION
**Pull request by Arthurk12**
### What does this PR do?
- [fix(layout): remove unused action](https://github.com/bigbluebutton/bigbluebutton/commit/d7d97645fc3e3dcba1504a5c92b7aa5e4133aa6d) 
Removes layout context action to set layout autoarrange option that was never used.
- [fix(layout): removes unused property](https://github.com/bigbluebutton/bigbluebutton/commit/a24781235141497132606d5aa70d9c3c61c52433) 
Removes unused property called SidebarContentHorizontalResizer that was not set or changed anywere in the code.
- [fix(layout): ensure the camera position is not undefined](https://github.com/bigbluebutton/bigbluebutton/commit/1c9482444f6db8f431283b30048b28219ffbe180) 

When changing from one layout to another, there is a merge of the previous input values with some of new values of the new layout. It happens that sometimes the previous layout didn't initialized the value for the camera dock position, leaving it as undefined and causing it to insert an inconsistent state to the next layout state. So this commit fixes it by initializing the camera position in all layouts types, to ensure its value in the layout input is not undefined. 

### Closes Issue(s)
Closes #23398

### How to test
Steps are given in the issue report.

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx [hunk 1]
```diff
@@ -168,6 +165,7 @@ const CustomLayout = (props) => {
                 },
               },
               cameraDock: {
+                position: CAMERADOCK_POSITION.CONTENT_TOP,
```
Comment (ramonlsouza) [inline bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx]: Can we use the initial values as a fallback (in every layout) instead of always resetting them on layout change? 

That way, if the user adjusts the camera position in Custom layout, switches to another layout, and then returns to Custom, their changes will be preserved.

```suggestion
                position: cameraDock.position || CAMERADOCK_POSITION.CONTENT_TOP,
```


https://github.com/user-attachments/assets/13c680c7-7505-430a-afef-d07b969ffdb4

File: bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx [hunk 2]
```diff
@@ -229,6 +224,7 @@ const CustomLayout = (props) => {
...
```
Comment (ramonlsouza) [inline bigbluebutton-html5/imports/ui/components/layout/layout-manager/customLayout.jsx]:
```suggestion
                position: cameraDock.position || CAMERADOCK_POSITION.CONTENT_TOP,
```

File: bigbluebutton-html5/imports/ui/components/layout/layout-manager/mediaOnlyLayout.jsx [hunk 3]
```diff
@@ -482,6 +480,7 @@ const MediaOnlyLayout = (props) => {
               },
             },
             cameraDock: {
+              position: CAMERADOCK_POSITION.CONTENT_LEFT,
```
Comment (ramonlsouza) [inline bigbluebutton-html5/imports/ui/components/layout/layout-manager/mediaOnlyLayout.jsx]:
```suggestion
              position: cameraDock.position || CAMERADOCK_POSITION.CONTENT_LEFT,
```

File: bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx [hunk 4]
```diff
@@ -121,6 +118,7 @@ const PresentationFocusLayout = (props) => {
               },
             },
             cameraDock: {
+              position: CAMERADOCK_POSITION.SIDEBAR_CONTENT_BOTTOM,
```
Comment (ramonlsouza) [inline bigbluebutton-html5/imports/ui/components/layout/layout-manager/presentationFocusLayout.jsx]:
```suggestion
              position: cameraDock.position || CAMERADOCK_POSITION.SIDEBAR_CONTENT_BOTTOM,
```

File: bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx [hunk 5]
```diff
@@ -113,6 +110,7 @@ const SmartLayout = (props) => {
               },
             },
             cameraDock: {
+              position: CAMERADOCK_POSITION.CONTENT_TOP,
```
Comment (ramonlsouza) [inline bigbluebutton-html5/imports/ui/components/layout/layout-manager/smartLayout.jsx]:
```suggestion
              position: cameraDock.position || CAMERADOCK_POSITION.CONTENT_TOP,
```

**Review by ramonlsouza — APPROVED** [review]
