### PR TITLE
Prevent Yes/No Quick Poll Without Options or Question

### LINKED ISSUE #16013: 2.5.8: yes/no quick poll partially crashes client when not preceded by text
**Describe the bug**
With the addition of #15856 to 2.5.8 quick polls add option texts pulled out from the slide. This appears to be sensitive to punctuation marks, i.e. if for example the "(yes/no)" is accidentally put _after_ a question mark this is the same as putting (yes/no) without any text at all. Starting such a poll makes a weird option-less poll appear for attendees and attempting to publish its results causes the presentation area of the client to crash and requires a restart of the meeting to work again (reloading the page doesn't suffice).

**To Reproduce**
1. Upload this pdf in the presentation manager: [quickpollcrash_258.pdf](https://github.com/bigbluebutton/bigbluebutton/files/10022453/quickpollcrash_258.pdf)
2. Navigate to the second slide
3. Press the [YES/NO] quick poll button
4. Press publish results button

**Expected behavior**
A poll with no custom option texts should appear (as it did before 2.5.8). Nothing should crash^^

**Actual behavior**
A poll popup with no actual button to click on appears for attendees (see screenshot). When the presenter publishes this poll's results, the presentation area of the client crashes and the meeting has to be ended and restarted for everything to work again.

**Screenshots**
The poll as it looks like to attendees:
Screenshot_2022-11-16_10-38-55

After "publish poll":

Screenshot_2022-11-16_10-41-42

### PR DESCRIPTION
**Pull request by KDSBrowne**
### What does this PR do?
This ensures that yes / no polls initiated via smart slides displays the question and options for the cases described in the issue below.
### Closes Issue(s)
Closes #16013

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/presentation/service.js [hunk 1]
```diff
@@ -95,6 +95,11 @@ const parseCurrentSlideContent = (yesValue, noValue, abstentionValue, trueValue,
   const pollRegex = /[1-9A-Ia-i][.)].*/g;
   let optionsPoll = safeMatch(pollRegex, content, []);
   const optionsWithLabels = [];
+
+  if (hasYN) {
+    optionsPoll = ['Yes', 'No'];
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/presentation/service.js:100]: Does this interfere with YN polls in other languages?

Comment (KDSBrowne) [reply bigbluebutton-html5/imports/ui/components/presentation/service.js]: Updated to use formatted labels

**Review by ramonlsouza — APPROVED** [review]

**Review by antobinary — APPROVED** [review]
LGTM!
