### PR TITLE
Fix links in welcome message

### LINKED ISSUE #6709: Welcome message should strip out event: from links
In the Flash client, the welcome message had clickable links written as

~~~
<a href="event:https://bigbluebuttion.org">bigbluebutton.org</a>
~~~
need to strip out `event:` from the link for it to work in the HTML5 client.

### PR DESCRIPTION
**Pull request by BobakOftadeh**
Closes #6709.

### CODE REVIEW

File: bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js [hunk 1]
```diff
@@ -81,10 +83,12 @@ export default function addMeeting(meeting) {
     setBy: 'temp',
   };
 
+  newMeeting.welcomeProp.welcomeMsg = newMeeting.welcomeProp.welcomeMsg.replace('event:', '');
```
Comment (antobinary) [inline bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js]: Did you try matching more of the context - like `href="event:`. I want to avoid the case where welcome message

```
Welcome to the conference, we hope you enjoy our event:
* point 1
...
```

gets matched and modified.

File: bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js [hunk 2]
```diff
@@ -66,6 +66,8 @@ export default function addMeeting(meeting) {
     metadataProp: Object,
   });
 
+  const newMeeting = meeting;
```
Comment (antobinary) [inline bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js]: Not sure if you need this copy. 
`meeting.welcomeProp.welcomeMsg = meeting.welcomeProp.welcomeMsg.replace(................')` could work too?

Comment (KDSBrowne) [reply bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js]: I think he did it this way to avoid a lint error.
`Disallow Reassignment of Function Parameters (no-param-reassign)`

Comment (antobinary) [reply bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js]: I guess the right way to say it is Bobak wanted to avoid the `Reassignment of Function Parameters ` :+1: Makes sense now, tnx Kert

File: bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js [hunk 3]
```diff
@@ -83,7 +83,12 @@ export default function addMeeting(meeting) {
     setBy: 'temp',
   };
 
-  newMeeting.welcomeProp.welcomeMsg = newMeeting.welcomeProp.welcomeMsg.replace('event:', '');
+  newMeeting.welcomeProp.welcomeMsg = newMeeting.welcomeProp.welcomeMsg.replace(
+    'href="event:',
+    'href="',
+  );
+
+  newMeeting.welcomeProp.welcomeMsg = newMeeting.welcomeProp.welcomeMsg.replace(/href/g, 'target="_blank" href');
```
Comment (KDSBrowne) [inline bigbluebutton-html5/imports/api/meetings/server/modifiers/addMeeting.js]: This is going to create a duplication of the `target` prop for the second link in the `welcomeMsg` string, consider this alternative:

```
  const insertBlankTarget = (s,i) => s.substr(0, i) + ' target="_blank"' + s.substr(i);
  const linkWithoutTarget = new RegExp(`<a href="(.*?)">`, 'g');
  linkWithoutTarget.test(newMeeting.welcomeProp.welcomeMsg);

  if (linkWithoutTarget.lastIndex > 0) {
    newMeeting.welcomeProp.welcomeMsg = insertBlankTarget(
      newMeeting.welcomeProp.welcomeMsg,
      linkWithoutTarget.lastIndex - 1
    );
  }
```
