### PR TITLE
Fix(html5): Space bar key problem on WB

### LINKED ISSUE #22079: Spacebar issue with infinite whiteboard
**Describe the bug**
Spacebar can be used as a hotkey for the hand tool. However, if the infinite whiteboard is toggled on, pressing down the spacebar and dragging mouse does not move the whiteboard.

**To Reproduce**
1. Switch on infinite whiteboard
2. Click on the whiteboard to get correct focus
3. Press and hold the spacebar. The cursor changes to hand. Click mouse button (the cursor reacts appropriately) and try to move the whiteboard 
4. Nothing happens
5. Release the spacebar, click the hand tool on the tool bar, try to drag the whiteboard again
6. All works as expected

**Expected behavior**
Holding the spacebar must have the same effect as selacting the hand tool.

**BBB version:**
BigBlueButton continually evolves. Providing the version/build helps us to pinpoint when an issue was introduced.
BigBlueButton Server 3.0.0-rc.1 (2065)

**Desktop (please complete the following information):**
 - OS: Ubuntu 22.04
 - Browser Chrome
 - Version latest

### PR DESCRIPTION
**Pull request by Tainan404**
### What does this PR do?
The issue was caused by aconflict between our handler and the Tldraw internal handler.

### Closes Issue(s)
Closes #22079

### How to test
- turn on infinite WB
- click on wb to focus
- press space to change the tool
- move mouse arround to pan the slide

### More

[Screencast from 17-02-2026 08:50:49.webm](https://github.com/user-attachments/assets/fd19d10c-5910-43e9-8c32-4bd0383f6f41)

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx [hunk 1]
```diff
@@ -616,7 +616,9 @@ const Whiteboard = React.memo((props) => {
       return;
     }
 
-    if (key === ' ' && tlEditorRef.current?.getCurrentToolId() !== 'hand' && isPresenterRef.current) {
+    if (event.keyCode === KEY_CODES.SPACE && tlEditorRef.current?.getCurrentToolId() !== 'hand' && isPresenterRef.current) {
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx]: The code change seems to fix the behavior, well done!
I'll just comment that if we move the check for is presenter, we likely save some cpu cycles for the non-presenter case (most users). And if presenter - no gain, no loss.

```suggestion
    if (isPresenterRef.current && event.keyCode === KEY_CODES.SPACE && tlEditorRef.current?.getCurrentToolId() !== 'hand') {
```

**Review by antobinary — APPROVED** [review]
Read through the code changes.
Tested locally with a main room, with and without infinite wb enabled.
