### PR TITLE
Fix webcam size after minimize the presentation

### LINKED ISSUE #7570: Webcam do not adjust size after minimize the presentation

### PR DESCRIPTION
**Pull request by vitormateusalmeida**
Closes #7570

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx [hunk 1]
```diff
@@ -146,6 +150,7 @@ export default class WebcamDraggableOverlay extends Component {
       && !resetPosition) this.setResetPosition(true);
 
     window.addEventListener('resize', this.eventResizeListener);
+    window.addEventListener('videoFocusChange', this.eventVideoFocusChangeListener);
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx]: Should remove listener on componentUnmount

File: bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx [hunk 2]
```diff
@@ -313,6 +333,13 @@ export default class WebcamDraggableOverlay extends Component {
     }
   }
 
+  eventVideoFocusChangeListener() {
+    setTimeout(() => {
+      this.setInitialReferencePoint();
+      this.setLastWebcamPosition();
+    }, 500);
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx]: Why do we need the timeout here?

Comment (vitormateusalmeida) [reply bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx]: I need to wait for the component modification for recalculate the position.

File: bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx [hunk 3]
```diff
@@ -88,23 +97,38 @@ class VideoList extends Component {
...
+      [styles.videoListSwapLayout]: swapLayout,
+    });
+
     return (
       <div
         ref={(ref) => { this.canvas = ref; }}
-        className={styles.videoCanvas}
+        className={canvasClassName}
+
+        // TODO adicionar videoCanvasSwapLayout quando for swaplayout
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/video-provider/video-list/component.jsx]: should be `// POR FAZER` /s

File: bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx (hunk 2 above)
Comment (prlanzarin) [reply bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx]: Can't the webcam pos/reference point calls be tethered to component state changes, then? I see that they're enveloped on async setTimeouts on almost every call when there's a change event of some sort (focus, resize). I worry it might be flaky on low end computers anyways (timeouts always are).

**Comment by antobinary** [comment]
Follow ups changes should address #7598 and #7573

File: bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx (hunk 2 above)
Comment (vitormateusalmeida) [reply bigbluebutton-html5/imports/ui/components/media/webcam-draggable-overlay/component.jsx]: Did it because this component need to look for the DOM. Can't use only the refs or state components. For this, use the react lifecycle causes a cascade events.
