### PR TITLE
fix(livekit): indicate user has left audio in user list/camera containers

### LINKED ISSUE #23732: With LiveKit, leaving the audio bridge looks the same as muted
**Describe the bug**
With LiveKit, leaving the audio bridge looks the same as muted, which would lead participants to believe the user can still hear them.

**To Reproduce**
On a BigBlueButton 3.0 server with LiveKit enabled,

1. Join Audio and then mute (red microphone icon visible on avatar)
2. Leave Audio bridge (red microphone icon still visible on avatar)

**Expected behavior**
When leaving audio, there would be no visible icon.  It would show the "bite" to indicate this user is unable to hear.

**Actual behavior**

See video below

https://github.com/user-attachments/assets/368d97b5-a965-4ee8-83dc-5076b23279a2

**BBB version:**
3.0.13 with LiveKit enabled

### PR DESCRIPTION
**Pull request by AtilaU19**
### What does this PR do?
This PR introduces changes to correctly represent the deafened state:

- In the User List, a deafened user is now treated as having `noVoice`,
  which hides the microphone/headset icon on their avatar.
- On a user's video stream, if they are deafened, all other audio
  status icons (muted, unmuted, listen-only) are now hidden.

### Closes Issue(s)

Closes https://github.com/bigbluebutton/bigbluebutton/issues/23732

### More
 - bbb-webrtc-sfu
 
[Screencast from 04-09-2025 14:21:32.webm](https://github.com/user-attachments/assets/eac418cc-f99a-4b37-8ad9-27809922ffcc)

 - livekit
 
[Screencast from 04-09-2025 14:22:55.webm](https://github.com/user-attachments/assets/9f10612e-e9f2-4919-8793-57a1191db400)

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx [hunk 1]
```diff
@@ -93,6 +94,11 @@ const Emoji: React.FC<EmojiProps> = ({ emoji, native, size }) => (
 );
 
 const UserListItem: React.FC<UserListItemProps> = ({ user, lockSettings, index }) => {
+  const { data: meeting } = useMeeting((m) => ({
+    audioBridge: m.audioBridge,
+  }));
+  const isLiveKit = meeting?.audioBridge === 'livekit';
+
```
Comment (prlanzarin) [inline bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx]: I think this doesn't need to be LiveKit specific.
Other bridge users should also be flagged as "not in audio" if they're deafened - even though the deafen primitive is currently not used for them.
Having a generic check here makes this future-proof and simpler.
(See subsequent review comment)


```suggestion
```

File: bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx [hunk 2]
```diff
@@ -19,6 +19,7 @@ import { useIsReactionsEnabled } from '/imports/ui/services/features';
 import useWhoIsTalking from '/imports/ui/core/hooks/useWhoIsTalking';
 import useWhoIsUnmuted from '/imports/ui/core/hooks/useWhoIsUnmuted';
 import { getSettingsSingletonInstance } from '/imports/ui/services/settings';
+import useMeeting from '/imports/ui/core/hooks/useMeeting';
```
Comment (prlanzarin) [inline bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx]: See two subsequent review comments.

```suggestion
```

File: bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx [hunk 3]
```diff
@@ -240,8 +246,12 @@ const UserListItem: React.FC<UserListItemProps> = ({ user, lockSettings, index }
...
         muted={voiceUser?.muted}
         listenOnly={voiceUser?.listenOnly || voiceUser?.listenOnlyInputDevice}
-        voice={voiceUser?.joined}
-        noVoice={!voiceUser?.joined}
+        voice={isLiveKit
+          ? (voiceUser?.joined && !voiceUser?.deafened)
+          : voiceUser?.joined}
+        noVoice={isLiveKit
+          ? (voiceUser?.joined && voiceUser?.deafened)
+          : !voiceUser?.joined}
```
Comment (prlanzarin) [inline bigbluebutton-html5/imports/ui/components/user-list/user-list-content/user-participants/user-list-participants/list-item/component.tsx]: I think this doesn't need to be LiveKit specific.
Other bridge users should also be flagged as "not in audio" if they're deafened - even though the deafen primitive is currently not used for them.
Having a generic check here makes this future-proof and simpler.
(See previous review comment)

```suggestion
        voice={voiceUser?.joined && !voiceUser?.deafened}
        noVoice={!voiceUser?.joined || voiceUser?.deafened}
```

File: bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-status/component.tsx [hunk 4]
```diff
@@ -19,15 +20,22 @@ const UserStatus: React.FC<UserStatusProps> = (props) => {
...
-      {listenOnly && <Styled.Voice iconName="listen" /> }
-      {(voiceUserJoined && !muted) && <Styled.Voice iconName="unmute" />}
+
+      {!deafened && (
+        <>
+          {(muted && !listenOnly) && <Styled.Muted iconName="unmute_filled" />}
+          {listenOnly && <Styled.Voice iconName="listen" />}
+          {(voiceUserJoined && !muted) && <Styled.Voice iconName="unmute" />}
+        </>
+      )}
```
Comment (prlanzarin) [inline bigbluebutton-html5/imports/ui/components/video-provider/video-list/video-list-item/user-status/component.tsx]: In the same vein as previous suggestions, this can be further simplified and made a bit more future-proof. The deafened state also defines whether an user is in audio - use it to generate the voiceUserJoined state simplify the rendering below. E.g.:


```
const UserStatus: React.FC<UserStatusProps> = (props) => {
  const { voiceUser, user, stream } = props;
  const data = { ...user, ...stream };

  const listenOnly = voiceUser?.listenOnly;
  const muted = voiceUser?.muted;
  const deafened = voiceUser?.deafened;
  const voiceUserJoined = voiceUser?.joined && !deafened;
  const emoji = data?.reactionEmoji;
  const away = data?.away;

  return (
    <div>
      {away && <span>⏰</span>}
      {(emoji && emoji !== 'none' && !away) && <span>{emoji}</span>}

      {voiceUserJoined && (
        <>
          {(muted && !listenOnly) && <Styled.Muted iconName="unmute_filled" />}
          {listenOnly && <Styled.Voice iconName="listen" />}
          {!muted && <Styled.Voice iconName="unmute" />}
        </>
      )}
    </div>
  );
};```

**Review by prlanzarin — CHANGES_REQUESTED** [review]
See review comments.

File: bigbluebutton-html5/imports/ui/core/hooks/useWhoIsDeafened.ts [hunk 5]
```diff
@@ -0,0 +1,103 @@
+import { useEffect } from 'react';
```
Comment (prlanzarin) [inline bigbluebutton-html5/imports/ui/core/hooks/useWhoIsDeafened.ts]: This hook likely can be substituted by adding the `deafened` attribute to the video streams subscription - it's only used once.
It'd save an user list subscription (or, alternatively, having to add the attribute to the user_activity table and extend that subscription instead).

See https://github.com/bigbluebutton/bigbluebutton/blob/ed612d3d2f2e7b323a4c2668ad0e5659a70e35f4/bigbluebutton-html5/imports/ui/components/video-provider/queries.ts#L31-L36.

**Review by prlanzarin — APPROVED** [review]
