### PR TITLE
Fix DOM injection in number of rooms select

### LINKED ISSUE #7517: Limit max number of breakouts (UI portion)
We already have a PR making changes to the back end: #7507 . Here the goal will be to address:

* Handle `maxNumberOfBreakouts` property in `addMeeting` code in the HTML5 server side.
*  Do not show higher nax for breakout rooms than the max.

### PR DESCRIPTION
**Pull request by Tainan404**
Closes #7517.

### CODE REVIEW

File: bigbluebutton-html5/imports/api/breakouts/server/methods/createBreakout.js [hunk 1]
```diff
@@ -18,7 +18,7 @@ export default function createBreakoutRoom(credentials, rooms, durationInMinutes
   check(requesterToken, String);
 
   const eventName = 'CreateBreakoutRoomsCmdMsg';
-
+  if (rooms.length > 8) return Logger.info(`Attempt to create breakout rooms with invalid number of rooms in meeting id=${meetingId}`);
```
Comment (jfsiebel) [inline bigbluebutton-html5/imports/api/breakouts/server/methods/createBreakout.js]: Shouldn't the max number of rooms be a meeting property?

Comment (Tainan404) [reply bigbluebutton-html5/imports/api/breakouts/server/methods/createBreakout.js]: I don't think so, from the beginning we decided to do it hard coded in the client, First version I did it in the settings, but was requested to change for hard code

Comment (antobinary) [reply bigbluebutton-html5/imports/api/breakouts/server/methods/createBreakout.js]: In https://github.com/bigbluebutton/bigbluebutton/pull/7507/files :

`There needs to be a hard cap of 9 breakout rooms or other parts of the application won't work. One problematic part would be the voice bridge generation.`

**Comment by jfsiebel** [comment]
Tested and worked well.

Just a little thing, we still use the injected number to render the number of boxes.
image

File: bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx [hunk 2]
```diff
@@ -383,6 +383,7 @@ class BreakoutRoom extends Component {
       valid,
       numberOfRooms,
     } = this.state;
+    const rooms = (numberOfRooms > MAX_BREAKOUT_ROOMS) ? 0 : numberOfRooms;
```
Comment (jfsiebel) [inline bigbluebutton-html5/imports/ui/components/actions-bar/create-breakout-room/component.jsx]: You should check for MIN_BREAKOUT_ROOMS too, because it's possible to put a negative number
