### PR TITLE
Fix moderator being able to stop recording when it aren't allowed

### LINKED ISSUE #7031: User can click stop recording when allowStartStopRecording=false&autoStartRecording=true
A user can click on the button to stop the recording, when allowStartStopRecording=false&autoStartRecording=true and after confirm nothing happens

### PR DESCRIPTION
**Pull request by Tainan404**
Closes #7031.

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx [hunk 1]
```diff
@@ -51,6 +51,7 @@ class RecordingIndicator extends React.PureComponent {
       time,
       amIModerator,
       intl,
+      allowStartStopRecording,
```
Comment (capilkey) [inline bigbluebutton-html5/imports/ui/components/nav-bar/recording-indicator/component.jsx]: The new property also needs to be added to the propTypes and defaultProps if it isn't required.
