### PR TITLE
Full screen button fix

### LINKED ISSUE #5397: Exit fullscreen button shows incorrectly 'make fullscreen'

### PR DESCRIPTION
**Pull request by BobakOftadeh**
#5397 

The correct full screen button now displays when the client is in full screen.

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx [hunk 1]
```diff
@@ -71,6 +71,7 @@ class SettingsDropdown extends Component {
 
     this.state = {
       isSettingOpen: false,
+      isFullScreen: false,
```
Comment (KDSBrowne) [inline bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx]: The state of `isFullScreen`, is already passed down as a prop from the container. I don't think we need to duplicate it here.

File: bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx [hunk 2]
```diff
@@ -79,16 +80,52 @@ class SettingsDropdown extends Component {
...
 
   componentWillMount() {
-    const { intl, isFullScreen, mountModal } = this.props;
+    this.createMenu();
+  }
+
+  componentWillReceiveProps(nextProps) {
+    this.setState(
+      { isFullScreen: nextProps.isFullScreen },
+      () => this.createMenu(),
```
Comment (KDSBrowne) [inline bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx]: Instead of creating the entire menu every time `componentWillReceiveProps`  runs, it would be better to only update the menu item that needs updating.

File: bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx [hunk 3]
```diff
@@ -79,18 +79,36 @@ class SettingsDropdown extends Component {
   }
 
   componentWillMount() {
-    const { intl, isFullScreen, mountModal } = this.props;
+    this.createMenu(this.props);
```
Comment (KDSBrowne) [inline bigbluebutton-html5/imports/ui/components/nav-bar/settings-dropdown/component.jsx]: `this.props` doesn't need to be passed to `createMenu()`, you can just use `this.props` inside `createMenu()`
