### PR TITLE
CI: avoid using some external/3rd party assets

### LINKED ISSUE #24849: CI: avoid using some external/3rd party assets
**Describe the bug**

Some CI/playwright variables use external assets from either 3rd parties or internal sources that are _not_ guaranteed to be serving the necessary asset as desired.

They should be moved to a more stable storage - either versioned within the repo (ok if text or _very small_ binary) or a stable data bucket controlled by the maintainers for this specific goal (CI/tests). Otherwise, we risk spurious CI failures.

The CI BBB instance itself could serve the files for client access if versioned locally.

References I found:
- https://github.com/bigbluebutton/bigbluebutton/blob/82408a2bc0648d517fa7f8d49f64693e5d07ada1/bigbluebutton-tests/playwright/parameters/constants.ts#L21
- https://github.com/bigbluebutton/bigbluebutton/blob/82408a2bc0648d517fa7f8d49f64693e5d07ada1/bigbluebutton-tests/playwright/parameters/constants.ts#L52
- https://github.com/bigbluebutton/bigbluebutton/blob/82408a2bc0648d517fa7f8d49f64693e5d07ada1/bigbluebutton-tests/playwright/parameters/constants.ts#L59
- https://github.com/bigbluebutton/bigbluebutton/blob/82408a2bc0648d517fa7f8d49f64693e5d07ada1/bigbluebutton-tests/playwright/parameters/constants.ts#L77-L78

**Expected behavior**

Use stable references to assets use by test/CI scripts.

**Actual behavior**

Assets pulled from 3rd parties and unstable sources.

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

Adjusts the following tests to not use external assets:
- Custom Styles: URL
- Override default presentation on CREATE meeting API call
- Display Branding Area
- Set webcam background by passing URL

### Closes Issue(s)
Closes #24849

### CODE REVIEW

File: bigbluebutton-tests/playwright/parameters/constants.ts [hunk 1]
```diff
@@ -18,7 +24,7 @@ export const constants = {
   lockSettingsHideUserList: 'lockSettingsHideUserList=true',
   allowModsToEjectCameras: 'allowModsToEjectCameras=true',
   notifyRecordingIsOn: 'notifyRecordingIsOn=true&notifyRecordingIsOn=true',
-  preUploadedPresentation: 'preUploadedPresentation=https://dagrs.berkeley.edu/sites/default/files/2020-01/sample.pdf',
+  preUploadedPresentation: `preUploadedPresentation=${serverOrigin}/default.pdf`,
```
Comment (antobinary) [inline bigbluebutton-tests/playwright/parameters/constants.ts]: There was something peculiar about that specific presentation. Can we consider downloading it to ...
maybe a github repo and linking to there?

**Review by Tainan404 — APPROVED** [review]
