### PR TITLE
Prevent settings modal re-opening after dismiss

### LINKED ISSUE #5637: Last close window is re-opened when opening chat
The following behaviour have been noticed in the HTML5 client. It only happens on a fresh meeting for the first user only.

**Steps to reproduce**

- Create a fresh meeting.
- Join the meeting.
- Open settings window.
- Close settings window.
- Click on public chat or private chat with another user.

**Noticed behaviour**
The settings window will re-open.

**Expected behaviour**
The settings window should not re-open.

### PR DESCRIPTION
**Pull request by KDSBrowne**
Fixes #5637

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/settings/component.jsx [hunk 1]
```diff
@@ -228,7 +228,10 @@ class Settings extends Component {
           description: intl.formatMessage(intlMessages.SaveLabelDesc),
         }}
         dismiss={{
-          callback: () => Settings.setHtmlFontSize(this.state.saved.application.fontSize),
+          callback: () => {
+            Settings.setHtmlFontSize(this.state.saved.application.fontSize);
+            this.props.mountModal(null);
```
Comment (Tainan404) [inline bigbluebutton-html5/imports/ui/components/settings/component.jsx]: The mountModal is used in confirm and dismiss callbacks. Can you destruct it and use directly?
