### PR TITLE
Fix chat input between chats

### LINKED ISSUE #6601: Chat input box should not carry [unsent] text between chats
Currently if you start typing in public chat input box (for example) and then you switch to chat with userA, the unsent text will be carried over to the chat with userA (if you press Enter at this point, it will be sent over)
One solution would be to store the unsent chat input so we can switch from one carryover to another when iterating between open chats.
Another option would be to clear the the chat input box any time you change the chat (inferior solution imo)
Comments?

### PR DESCRIPTION
**Pull request by vitormateusalmeida**
Closes #6601

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx [hunk 1]
```diff
@@ -51,20 +52,41 @@ class MessageForm extends PureComponent {
   }
 
   componentDidMount() {
+    const { chatId } = this.props;
     const { mobile } = this.BROWSER_RESULTS;
+    const { UnsentMessagesCollection } = ChatService;
```
Comment (Tainan404) [inline bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx]: Would consider get this from props coming from container

File: bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx [hunk 2]
```diff
@@ -51,20 +52,41 @@ class MessageForm extends PureComponent {
...
       this.textarea.focus();
     }
+
+    if (prevProps.chatId !== chatId) {
+      UnsentMessagesCollection.upsert(
+        { chatId: prevProps.chatId },
+        { $set: { message } },
+      );
+
+      const unsentMessageByChat = UnsentMessagesCollection.findOne({ chatId });
```
Comment (Tainan404) [inline bigbluebutton-html5/imports/ui/components/chat/message-form/component.jsx]: you have the same logic in `componentDidMount`, pass to a function to reuse
