### PR TITLE
Tweak viewer controls for external video component

### LINKED ISSUE #12802: External video player - refresh button tweaks
**Describe the bug**
The refresh button is not correctly positioned and is missing internationalization

**To Reproduce**
1. Join a meeting with two users - moderator and viewer
[1.1]. (I am able to reproduce this in Smart layout, possibly other layouts might be affected) Set the layout to Smart layout
2. Moderator starts external video share (via + button)
3. Viewer hovers over the video and the refresh button appears

**Expected behavior**
The refresh button is supposed to be overlaying the videp

**Actual behavior**
The refresh button is hovering in the top left-hand corner of the client

**Screenshots**

Screenshot from 2021-07-21 11-51-18
Screenshot from 2021-07-21 11-53-46

**BBB version:**
BigBlueButton 2.4 alpha1 + https://github.com/bigbluebutton/bigbluebutton/pull/12181

### PR DESCRIPTION
**Pull request by Tainan404**
### What does this PR do?
Tweak buttons for external video player and implement viewer bahavior

Note: in mobile I added a overlay on video player, bacause the player is a Iframe and iframe doesn't propagate events to parents, so, to catch the events of `touchstart` and `touchend` I've to add it.

### Closes Issue(s)
Closes #12802

### CODE REVIEW

**Review by lfzawacki — CHANGES_REQUESTED** [review]
I'd like some changes as requested in my comments

File: bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx [hunk 1]
```diff
@@ -412,144 +466,119 @@ class VideoPlayer extends Component {
...
+      volume, muted, key, showHoverToolBar,
     } = this.state;
 
+    const mobileHoverToolBarStyle = showHoverToolBar
+      ? styles.showMobileHoverToolbar
+      : styles.dontShowMobileHoverToolbar;
+    const desktopHoverToolBarStyle = styles.hoverToolbar;
+
+    const hoverToolbarStyle = this.isMobile ? mobileHoverToolBarStyle : desktopHoverToolBarStyle;
+    console.log('this.isMobile', this.isMobile);
```
Comment (ramonlsouza) [inline bigbluebutton-html5/imports/ui/components/external-video-player/component.jsx:492]: ^

**Review by ramonlsouza — CHANGES_REQUESTED** [review]
a warning is appearing for viewers:

Screenshot from 2021-08-06 08-16-43

video size is not the same as in develop:
video-size

can't click "play" button in mobile (because of controls overlay)

Screenshot from 2021-08-06 08-39-11

**Review by ramonlsouza — APPROVED** [review]
