### PR TITLE
fix: Ctrl+A shortcut selects objects at outside of whiteboard

### LINKED ISSUE #17029: [2.6] Ctrl+A shortcut selects objects at outside of whiteboard
**Describe the bug**
The Ctrl+A shortcut within the whiteboard selects objects at outside of the whiteboard.

**To Reproduce**
1. draw whatever shapes using the tool
2. push Ctrl+A to select all the shapes
3. Objects at outside the whiteboard are selected in addition to the whiteboard shapes

**Expected behavior**
The Ctrl+A key event should not propagate at outside of the whiteboard.

**Actual behavior**
It propagates and everything in the window is selected.

**Screenshots**
Animation1

**BBB version:**
The latest. 

**Desktop (please complete the following information):**
 - Windows
 - Brave
 - the latest 64 bit

**Additional context**

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

Handle ctrl+A shortcut when the whiteboard is focused so it selects all shapes instead of selecting objects outside of the whiteboard.

### Closes Issue(s)
Closes #17029

### CODE REVIEW

**Review by KDSBrowne — APPROVED** [review]
Looks good! The select all shortcut works as expected.
select-all

**Comment by antobinary** [comment]
Well done!

File: bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx [hunk 1]
```diff
@@ -565,6 +565,13 @@ export default function Whiteboard(props) {
       case KEY_CODES.ENTER:
         fullscreenToggleHandler();
         break;
+      case KEY_CODES.A:
+        if (ctrlKey) {
+          event.preventDefault();
+          event.stopPropagation();
+          tldrawAPI?.selectAll();
```
Comment (hiroshisuga) [inline bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx:572]: Wouldn't
```
if (ctrlKey) {
  event.preventDefault();
}
```
be enough?
