### PR TITLE
 Fix End Meeting errors

### LINKED ISSUE #7021: HTML5 crashes if ending parent meeting while breakouts active
Peek 2019-03-14 09-48

### PR DESCRIPTION
**Pull request by vitormateusalmeida**
Closes #7021

### CODE REVIEW

**Comment by antobinary** [comment]
This pull request aims at resolving all current issues stemming from the fact that Meeting termination clears the model, leaving the clients to sync to a missing db object.

The new approach is to introduce a `       meetingEnded: true,` property when a meeting is terminating, and removing the actual data at a later point. This way we will not be "pulling the rug" from under the client and all data depending on the existence of Meeting object will persist

File: bigbluebutton-html5/imports/api/meetings/server/handlers/meetingEnd.js [hunk 1]
```diff
@@ -1,8 +1,26 @@
...
+
+  Breakouts.update({
+    parentMeetingId: meetingId,
+  }, {
+    $set: {
+      meetingEnded: true,
+    },
+  });
+
+  return setTimeout(() => removeMeeting(meetingId), 10000);
```
Comment (antobinary) [inline bigbluebutton-html5/imports/api/meetings/server/handlers/meetingEnd.js]: Did you try different delays? What happens if we set the timeout to 1sec?

File: bigbluebutton-html5/imports/api/voice-users/server/modifiers/clearVoiceUsers.js [hunk 2]
```diff
@@ -4,11 +4,11 @@ import VoiceUsers from '/imports/api/voice-users';
 export default function clearVoiceUser(meetingId) {
   if (meetingId) {
     return VoiceUsers.remove({ meetingId }, () => {
-      Logger.info(`Cleared Users (${meetingId})`);
+      Logger.info(`Cleared clearVoiceUser (${meetingId})`);
```
Comment (antobinary) [inline bigbluebutton-html5/imports/api/voice-users/server/modifiers/clearVoiceUsers.js]: ...`Cleared VoiceUsers in`...

File: bigbluebutton-html5/imports/api/voice-users/server/modifiers/clearVoiceUsers.js [hunk 3]
```diff
@@ -4,11 +4,11 @@ import VoiceUsers from '/imports/api/voice-users';
...
     });
   }
 
   return VoiceUsers.remove({}, () => {
-    Logger.info('Cleared Users (all)');
+    Logger.info('Cleared clearVoiceUser (all)');
```
Comment (antobinary) [inline bigbluebutton-html5/imports/api/voice-users/server/modifiers/clearVoiceUsers.js]: ... `Cleared VoiceUsers in all meetings`...

File: bigbluebutton-html5/imports/startup/client/base.jsx [hunk 4]
```diff
@@ -28,14 +29,14 @@ const propTypes = {
   subscriptionsReady: PropTypes.bool.isRequired,
   locale: PropTypes.string,
   approved: PropTypes.bool,
-  meetingEnded: PropTypes.bool,
+  meetingIsEnded: PropTypes.bool,
```
Comment (antobinary) [inline bigbluebutton-html5/imports/startup/client/base.jsx]: meetingHasEnded would be better grammatically

File: bigbluebutton-html5/imports/startup/client/base.jsx [hunk 5]
```diff
@@ -28,14 +29,14 @@ const propTypes = {
...
   meetingExist: PropTypes.bool,
 };
 
 const defaultProps = {
   locale: undefined,
   approved: undefined,
-  meetingEnded: false,
+  meetingIsEnded: false,
```
Comment (antobinary) [inline bigbluebutton-html5/imports/startup/client/base.jsx]: I would think that this prop could be `.isRequired` especially since we set it to `false` on server side when adding meeting

File: bigbluebutton-html5/imports/startup/client/base.jsx [hunk 6]
```diff
@@ -64,6 +65,7 @@ class Base extends Component {
     this.state = {
       loading: false,
       meetingExisted: false,
+      isBreakout: false,
```
Comment (antobinary) [inline bigbluebutton-html5/imports/startup/client/base.jsx]: Why are you adding this? I'd be cautious here.

File: bigbluebutton-html5/imports/startup/client/base.jsx [hunk 7]
```diff
@@ -94,30 +95,20 @@ class Base extends Component {
...
-      Session.set('isMeetingEnded', false);
+    if (prevProps.meetingExist && !meetingExist && !meetingExisted) {
+      this.setMeetingExisted(true);
     }
 
-    if (prevProps.meetingExist && !meetingExist) {
-      Session.set('isMeetingEnded', true);
-      this.setMeetingExisted(true);
+    // In case the meteor restart avoid error log
+    if (meteorIsConnected && (prevState.meetingExisted !== meetingExisted) && meetingExisted) {
```
Comment (antobinary) [inline bigbluebutton-html5/imports/startup/client/base.jsx]:
```suggestion
    if (meteorIsConnected && meetingExisted && !prevState.meetingExisted) {
```

File: bigbluebutton-html5/imports/ui/components/app/container.jsx [hunk 8]
```diff
@@ -88,23 +83,7 @@ export default injectIntl(withModalMounter(withTracker(({ intl, baseControls })
...
-    },
-  });
-
-  // Close the window when the current breakout room ends
-  Breakouts.find({ breakoutId: Auth.meetingID }).observeChanges({
-    removed() {
-      Auth.clearCredentials().then(window.close);
-    },
-  });
+  if (meeting && meeting.meetingEnded) window.close();
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/app/container.jsx]: We are removing `.observeChanges{}`. Are you sure we are handling this reactively?

File: bigbluebutton-html5/imports/ui/components/toast/container.jsx [hunk 9]
```diff
@@ -80,5 +81,6 @@ export default injectIntl(injectNotify(withTracker(({ notify, intl }) => {
     hideProgressBar: false,
     closeOnClick: true,
     pauseOnHover: true,
+    meeting: Meetings.find({ meetingId }).fetch(),
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/toast/container.jsx]: Why .fetch()? Typically we use .findOne({meetingId})

File: bigbluebutton-html5/imports/startup/client/base.jsx [hunk 10]
```diff
@@ -144,34 +135,34 @@ class Base extends Component {
...
       return (<MeetingEnded code={ejectedReason} />);
     }
 
-    if ((meetingExisted && !meetingExist)) {
+    if (isMeetingBreakout && !isBreakout) this.setState({ isBreakout: true });
+
+    if (meetingIsEnded && !isBreakout) {
       AudioManager.exitAudio();
-      return (<MeetingEnded code={Session.get('codeError')} />);
+      return (<MeetingEnded code={codeError} />);
```
[the remark this answers is not in the document]
Comment (vitormateusalmeida) [reply bigbluebutton-html5/imports/startup/client/base.jsx]: In MeetingEnded Component the codeError is required
But, The Base Component not define a default value in case of the codeError not be able to found in Session
Should we set a default value for codeError?

File: bigbluebutton-html5/imports/startup/client/base.jsx [hunk 11]
```diff
@@ -279,9 +275,10 @@ const BaseContainer = withTracker(() => {
     breakoutRoomSubscriptionHandler,
     meetingModeratorSubscriptionHandler,
     animations,
-    meetingExist: !!Meetings.find({ meetingId }).count(),
     User,
     meteorIsConnected: Meteor.status().connected,
+    meetingExist: !!Meetings.find({ meetingId }).count(),
+    meetingIsEnded: !!meeting && meeting.meetingEnded,
```
[the remark this answers is not in the document]
Comment (vitormateusalmeida) [reply bigbluebutton-html5/imports/startup/client/base.jsx]: I need to check if meeting exist, because I can not find the value meetingHasEnded if the meeting not exist

File: bigbluebutton-html5/imports/ui/components/app/container.jsx (hunk 8 above)
Comment (vitormateusalmeida) [reply bigbluebutton-html5/imports/ui/components/app/container.jsx]: Yes

File: bigbluebutton-html5/imports/startup/client/base.jsx [hunk 12]
```diff
@@ -144,34 +135,34 @@ class Base extends Component {
...
+    const isMeetingBreakout = AppService.meetingIsBreakout();
 
     if (ejected && ejected.ejectedReason) {
       const { ejectedReason } = ejected;
       AudioManager.exitAudio();
       return (<MeetingEnded code={ejectedReason} />);
     }
 
-    if ((meetingExisted && !meetingExist)) {
+    if (isMeetingBreakout && !isBreakout) this.setState({ isBreakout: true });
```
[the remark this answers is not in the document]
Comment (vitormateusalmeida) [reply bigbluebutton-html5/imports/startup/client/base.jsx]: When is Breakout Room, this avoid MeetingEnded page loading and ensure Breakout Room window closes

File: bigbluebutton-html5/imports/ui/components/app/container.jsx (hunk 8 above)
Comment (Tainan404) [reply bigbluebutton-html5/imports/ui/components/app/container.jsx]: If this code is in a withTracker it will remain active

File: bigbluebutton-html5/imports/ui/components/toast/container.jsx (hunk 9 above)
Comment (Tainan404) [inline bigbluebutton-html5/imports/ui/components/toast/container.jsx]: You can use the findOne reference here instead call a new find.

File: bigbluebutton-html5/imports/startup/client/base.jsx [hunk 13]
```diff
@@ -279,9 +275,10 @@ const BaseContainer = withTracker(() => {
     breakoutRoomSubscriptionHandler,
     meetingModeratorSubscriptionHandler,
     animations,
-    meetingExist: !!Meetings.find({ meetingId }).count(),
     User,
     meteorIsConnected: Meteor.status().connected,
+    meetingExist: !!Meetings.find({ meetingId }).count(),
```
[the remark this answers is not in the document]
Comment (vitormateusalmeida) [reply bigbluebutton-html5/imports/startup/client/base.jsx]: This ensures that the result of the function will be consistent with the name and expected value of the variable

**Comment by vitormateusalmeida** [comment]
The last commit fix the console warning when there is a breakout room and the meeting is ended.
The observers was moved to Base because in Toast Container its were trying to update after unmount.

File: bigbluebutton-html5/imports/api/meetings/server/handlers/meetingEnd.js [hunk 14]
```diff
@@ -21,6 +23,7 @@ export default function handleMeetingEnd({ body }, meetingId) {
       meetingEnded: true,
     },
   });
+  Users.find({ meetingId }).fetch().map(user => setConnectionStatus(user.meetingId, user.userId, 'offline'));
```
Comment (antobinary) [inline bigbluebutton-html5/imports/api/meetings/server/handlers/meetingEnd.js]: Users.findOne({ meetingId }).map....

File: bigbluebutton-html5/imports/startup/client/base.jsx [hunk 15]
```diff
@@ -263,6 +283,55 @@ const BaseContainer = withTracker(() => {
...
+            'rooms',
+          );
+        }
+        breakoutNotified = true;
+      }
+    },
+  });
+
+  Meetings.find({ meetingId }).observe({
+    changed: (newDocument, oldDocument) => {
```
Comment (antobinary) [inline bigbluebutton-html5/imports/startup/client/base.jsx]: This could be a huge performance killer :thinking: 
Why do we need to know whether the recording status changed in Base?

Comment (vitormateusalmeida) [reply bigbluebutton-html5/imports/startup/client/base.jsx]: https://github.com/bigbluebutton/bigbluebutton/pull/7074#issuecomment-481379556
This code was causing errors where it was being called because it tried to perform an update after unmount
