### PR TITLE
fix(whiteboard): Unstable zoom when presentation area is resized

### LINKED ISSUE #21191: Incorrect zoom adjustment in Tldraw when resizing window
**Describe the bug**
When resizing the browser window to make it wider or narrower, Tldraw does not consistently adjust the zoom level correctly.

**To Reproduce**
1. Resize the application window by increasing or decreasing its width.
2. Observe that the whiteboard attempts to adjust to the new window size, but sometimes the zoom level is either too high or too low.

**Expected behavior**
Tldraw page should fit exactly within the presentation space, occupying 100% of the available area without being over-zoomed or under-zoomed.

**Actual behavior**
The zoom level occasionally becomes incorrect after resizing, causing the content not to fit properly within the canvas.

**Screenshots**

[Screencast from 2024-09-13 16-40-28.webm](https://github.com/user-attachments/assets/671a81c3-acaf-43af-83cc-22de77204e65)

**BBB version:**
BigBlueButton Server 3.0.0-beta.1 (1545)

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Browser Chrome

**Smartphone (please complete the following information):**
 - Browser [e.g. stock browser, Safari]
 - Version 128.0.6613.137 (Official Build) (64-bit)

### LINKED ISSUE #21302: [3.0] Whiteboard zooms in when joining meeting
**Describe the bug**
When the user joins the meeting and clicks outside the audio modal, the whiteboard zooms in.
I could reproduce this only with the moderator and attendee, for the presenter looks normal.

**To Reproduce**
1. Create a meeting
2. Join with a moderator or attendee
3. When the audio modal loaded, and the whiteboard is about to load, you must click very fast
4. It will zoom in the whiteboard.

**Video**

[recording (5).webm](https://github.com/user-attachments/assets/9bab41cc-07d0-4d58-8cb7-8577d4ea9565)

### LINKED ISSUE #22292: [3.0] Zoom out in focus presentation layout
**Describe the bug**
The presentation gets zoomed out when the presenter swaps to the "focus on presentation" layout.

**To Reproduce**
1. Create a meeting with two users
2. Share the webcams
3. Upload the presentation shared on this issue
4. Swap to the "focus on presentation" layout
5. See the zoomed out presentation for the presenter

**Presentation uploaded**

[100PagesFile.pdf](https://github.com/user-attachments/files/18798948/100PagesFile.pdf)

**Video**

https://github.com/user-attachments/assets/528d903d-50b9-4c0b-8540-432b567753f3

### PR DESCRIPTION
**Pull request by JoVictorNunes**
### What does this PR do?

Cancels previous polling for stable whiteboard container when the presentation area is resized. This way we guarantee that the polling queuing is done in the right order.

### Closes Issue(s)

Closes #22292
Closes #21302
Closes #21191

### CODE REVIEW

**Comment by antonbsa** [comment]
after many attempts, I could get the wrong zoom applied 2 times. it broke for the presenter and viewer but not at the same time. I've uploaded a .txt ("save chat" file) and was switching from this to the default presentation + resizing the window (using Win + arrow keys) right after it finished changing and applying the correct zoom. when the viewer got the bug, no changes on his end reverted the state, only after the presenter zoomed in, propagating to him.

- presenter:



- viewer:

File: bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx [hunk 1]
```diff
@@ -759,6 +765,7 @@ const Whiteboard = React.memo((props) => {
   };
 
   const handleTldrawMount = (editor) => {
+    console.log('Tldraw:mount');
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx:768]:
```suggestion

```

**Comment by antobinary** [comment]
Based on internal conversations, the consensus is that while there are still some cases with zoom instability, this work by @JoVictorNunes is a big step towards stability. I am merging it now so it can be available as part of BBB 3.0.0-rc.4.
Let's continue the work in the next PR, @JoVictorNunes :pray:
