### PR TITLE
Prevent users from sending private messages to offline user

### LINKED ISSUE #11815: [2.3] User can still send private messages to another offline user
To reproduce:
1. Connect with 2 users to a meeting
2. Start private chat messaging between the 2 users
3. Close a tab of one of the users and wait for the disconnected user to disappear from the users list
4. Click on the private chat tab with the disconnected user, type and send a private message to him
5. See result..

Expected behavior:
image

Current behavior:

https://user-images.githubusercontent.com/5144311/113042759-f1dc2300-9171-11eb-93c5-127c44d25b60.mp4

### PR DESCRIPTION
**Pull request by ramonlsouza**
### What does this PR do?

Prevent users from sending private messages to offline user, by locking message input if user is offline

#### important: 
should be merged after #11909

### Closes Issue(s)
Closes #11815

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/chat/container.jsx [hunk 1]
```diff
@@ -117,6 +122,20 @@ const ChatContainer = (props) => {
...
 
+  const { users } = usingUsersContext;
+  let partnerIsLoggedOut = false;
+
+  if(!isPublicChat){
+    const idUser = participants?.filter((user) => user.id !== Auth.userID)[0]?.id;
+    partnerIsLoggedOut = (users[idUser]?.loggedOut || users[idUser]?.ejected) ? true : false;
+
+    if (partnerIsLoggedOut) {
+      isChatLocked = true;
```
Comment (Tainan404) [inline bigbluebutton-html5/imports/ui/components/chat/container.jsx:133]: as a good practice, I recommend not reassigning the values of the props

**Review by Tainan404 — CHANGES_REQUESTED** [review]

File: bigbluebutton-html5/imports/ui/components/chat/container.jsx (hunk 1 above)
Comment (ramonlsouza) [reply bigbluebutton-html5/imports/ui/components/chat/container.jsx]: updated in 448d1b0
