### PR TITLE
fix(whiteboard): Properly handle line shape handles in akka

### LINKED ISSUE #20306: [3.0] Drawing not saving last undo state.
**Describe the bug**
When drawing a line, changing the line format, then undoing this action, and moving the line, it will get the line in the previous state with the line changed format.

**To Reproduce**
1. Create a meeting
2. Draw a line
3. Change the line format
4. Undo the action
5. Move the line
6. The line will return to the previous state before the undo action.

**Video**

lineNotSavingUndo

### PR DESCRIPTION
**Pull request by KDSBrowne**
### What does this PR do?
This PR adds functionality for handling line shape handles in akka. This ensures that the correct line shape data is transmitted to viewers, with the handles attribute properly overwritten instead of merged.

Additionally, it includes frontend checks to prevent unnecessary updates based on the meta properties of shapes. (related to #20070)

### Closes Issue(s)
Closes #20306,  #20340

### CODE REVIEW

File: bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx [hunk 1]
```diff
@@ -518,6 +518,13 @@ const Whiteboard = React.memo(function Whiteboard(props) {
         delete remoteShape.questionType;
         toAdd.push(remoteShape);
       } else if (!isEqual(localShape, remoteShape) && prevShape) {
+        if (
+          (remoteShape?.meta?.createdBy === currentUser?.userId && remoteShape?.meta?.updatedBy === currentUser?.userId)
```
Comment (antobinary) [inline bigbluebutton-html5/imports/ui/components/whiteboard/component.jsx:522]: Could we do something like

`const remoteShapeMeta = remoteShape?.meta;`
and then

`if (remoteShapeMeta && ....`

just to avoid 8 checks if remoteShape, if meta, etc
